/**
 * Content Safety Gate A — curated visual-generation blocklist.
 *
 * Derived from word-lists.ts (4,571 terms) via the NF8 re-tag pass
 * (docs/CONTENT_SAFETY_DESIGN.md D3, Rev 1 decision 6): every term was
 * classified for sexual/nudity/pornography INTENT in an image/video
 * generation prompt. Profanity, insults, and slurs are deliberately NOT
 * here — profanity alone never blocks (creators legitimately script
 * swearing), and hate-speech terms are not sexual-content requests.
 *
 * A language-blind collision pass dropped terms that are common innocent
 * words in other languages or domains (e.g. Turkish "am" = English "am",
 * "sperm" = sperm whale, "kinky" = hair type, Italian "sega" = SEGA,
 * ja katakana "カント" = Kant). Hasan's review pass (2026-08-26) dropped 41
 * further collision terms — English homonyms/idioms (fr "bite" = English
 * "bite", "snatch" = the Olympic lift, "fingering" = guitar charts…),
 * cross-language innocents (es "concha" = pastry/shell, nl "aftrekken" =
 * subtraction, ar "فرج" = relief…), and CJK terms that fire inside longer
 * words ("ローター" = rotor, "脱衣" in 脱衣所…). Rationale + verdicts are in
 * docs/CONTENT_SAFETY_DESIGN.md Rev 2 amendments; the pruned prompts are
 * pinned as golden tests in generation-gate.test.ts. Gate B (pixels) is the
 * security boundary, so Gate A drops trade no safety for the FP win.
 *
 * MINORS_TERMS below are sexualized-minor terms — hard block, first
 * curation priority; the block includes additions not present in the
 * source list because absence there is not a reason to omit them here.
 *
 * Matching runs through term-matcher.ts (normalizer variants incl. NFKC,
 * homoglyphs, leetspeak; word boundaries; no-space-script boundaries).
 */

import type { ModerationCategory, ModerationTerm } from './types';

/** Blocklist categories — 'profanity' is structurally excluded. */
export type GenerationBlockCategory = Exclude<ModerationCategory, 'profanity'>;

function t(
  term: string,
  category: GenerationBlockCategory,
  language: string,
  severity: ModerationTerm['severity'],
): ModerationTerm {
  return { term, category, language, severity };
}

/**
 * Sexualized-minor terms absent from the source list, added directly.
 * Highest priority of the whole gate; never remove without replacement.
 * Exported because this block stays enforced under the dev bypass too
 * (generation-gate.ts).
 */
export const MINORS_ADDITIONS: ModerationTerm[] = [
  t('child porn', 'sexual', 'en', 'high'),
  t('child pornography', 'sexual', 'en', 'high'),
  t('childporn', 'sexual', 'en', 'high'),
  t('kiddie porn', 'sexual', 'en', 'high'),
  t('kiddieporn', 'sexual', 'en', 'high'),
  t('kiddy porn', 'sexual', 'en', 'high'),
  t('csam', 'sexual', 'en', 'high'),
  t('loli', 'sexual', 'en', 'high'),
  t('lolicon', 'sexual', 'en', 'high'),
  t('toddlercon', 'sexual', 'en', 'high'),
  t('naked child', 'sexual', 'en', 'high'),
  t('naked children', 'sexual', 'en', 'high'),
  t('nude child', 'sexual', 'en', 'high'),
  t('nude children', 'sexual', 'en', 'high'),
  t('naked kid', 'sexual', 'en', 'high'),
  t('naked kids', 'sexual', 'en', 'high'),
  t('nude kid', 'sexual', 'en', 'high'),
  t('nude kids', 'sexual', 'en', 'high'),
  t('naked teen', 'sexual', 'en', 'high'),
  t('nude teen', 'sexual', 'en', 'high'),
  t('naked minor', 'sexual', 'en', 'high'),
  t('nude minor', 'sexual', 'en', 'high'),
];

const CURATED_TERMS: ModerationTerm[] = [
  // ── en (678 terms)
  t('0ral seks', 'sexual', 'en', 'high'),
  t('0ral sex', 'sexual', 'en', 'high'),
  t('0rg@sm', 'sexual', 'en', 'high'),
  t('0rgasms', 'sexual', 'en', 'high'),
  t('2 girls 1 cup', 'pornography', 'en', 'high'),
  t('2g1c', 'pornography', 'en', 'high'),
  t('3jakulating', 'sexual', 'en', 'high'),
  t('4skin', 'nudity', 'en', 'high'),
  t('acrotomophilia', 'sexual', 'en', 'high'),
  t('alabama hot pocket', 'sexual', 'en', 'high'),
  t('alaskan pipeline', 'sexual', 'en', 'high'),
  t('anal', 'sexual', 'en', 'high'),
  t('anal hole', 'nudity', 'en', 'high'),
  t('anal hore', 'sexual', 'en', 'high'),
  t('analingus', 'sexual', 'en', 'high'),
  t('analplug', 'sexual', 'en', 'high'),
  t('analplugs', 'sexual', 'en', 'high'),
  t('anilingus', 'sexual', 'en', 'high'),
  t('anus', 'nudity', 'en', 'high'),
  t('anus plug', 'sexual', 'en', 'high'),
  t('arsefuck', 'sexual', 'en', 'high'),
  t('ass fuck', 'sexual', 'en', 'high'),
  t('assfck', 'sexual', 'en', 'high'),
  t('assfk', 'sexual', 'en', 'high'),
  t('assfook', 'sexual', 'en', 'high'),
  t('assfuck', 'sexual', 'en', 'high'),
  t('auto erotic', 'sexual', 'en', 'high'),
  t('autoerotic', 'sexual', 'en', 'high'),
  t('b*ttf*ck', 'sexual', 'en', 'high'),
  t('b00bs', 'nudity', 'en', 'high'),
  t('b00bz', 'nudity', 'en', 'high'),
  t('babeland', 'pornography', 'en', 'high'),
  t('baby batter', 'sexual', 'en', 'high'),
  t('baby juice', 'sexual', 'en', 'high'),
  t('ball gag', 'sexual', 'en', 'high'),
  t('ball gravy', 'sexual', 'en', 'high'),
  t('ball licking', 'sexual', 'en', 'high'),
  t('ball sack', 'nudity', 'en', 'high'),
  t('ball sucking', 'sexual', 'en', 'high'),
  t('ballbag', 'nudity', 'en', 'high'),
  t('ballsack', 'nudity', 'en', 'high'),
  t('bangbros', 'pornography', 'en', 'high'),
  t('bangbus', 'pornography', 'en', 'high'),
  t('barely legal', 'sexual', 'en', 'high'),
  t('barenaked', 'nudity', 'en', 'high'),
  t('bastinado', 'sexual', 'en', 'high'),
  t('bater', 'sexual', 'en', 'high'),
  t('bbw', 'pornography', 'en', 'high'),
  t('bdsm', 'sexual', 'en', 'high'),
  t('beastial', 'sexual', 'en', 'high'),
  t('beastiality', 'sexual', 'en', 'high'),
  t('beastility', 'sexual', 'en', 'high'),
  t('beat my meat', 'sexual', 'en', 'high'),
  t('beat the meat', 'sexual', 'en', 'high'),
  t('beat your meat', 'sexual', 'en', 'high'),
  t('beaver cleaver', 'sexual', 'en', 'high'),
  t('beaver lips', 'nudity', 'en', 'high'),
  t('bell end', 'nudity', 'en', 'high'),
  t('bellend', 'nudity', 'en', 'high'),
  t('bestial', 'sexual', 'en', 'high'),
  t('bestiality', 'sexual', 'en', 'high'),
  t('bewbs', 'nudity', 'en', 'high'),
  t('big breasts', 'nudity', 'en', 'high'),
  t('big knockers', 'nudity', 'en', 'high'),
  t('big tits', 'nudity', 'en', 'high'),
  t('birdlock', 'sexual', 'en', 'high'),
  t('bj', 'sexual', 'en', 'high'),
  t('black cock', 'nudity', 'en', 'high'),
  t('blonde action', 'pornography', 'en', 'high'),
  t('blonde on blonde action', 'pornography', 'en', 'high'),
  t('blow a load', 'sexual', 'en', 'high'),
  t('blow job', 'sexual', 'en', 'high'),
  t('blow your load', 'sexual', 'en', 'high'),
  t('blowjob', 'sexual', 'en', 'high'),
  t('blowjobs', 'sexual', 'en', 'high'),
  t('blue waffle', 'pornography', 'en', 'high'),
  t('blumpkin', 'sexual', 'en', 'high'),
  t('blumpkin boy', 'sexual', 'en', 'high'),
  t('bondage', 'sexual', 'en', 'high'),
  t('boner', 'nudity', 'en', 'high'),
  t('bonk juice', 'sexual', 'en', 'high'),
  t('boob', 'nudity', 'en', 'high'),
  t('boobie', 'nudity', 'en', 'high'),
  t('boobs', 'nudity', 'en', 'high'),
  t('booobs', 'nudity', 'en', 'high'),
  t('boooobs', 'nudity', 'en', 'high'),
  t('booooobs', 'nudity', 'en', 'high'),
  t('booooooobs', 'nudity', 'en', 'high'),
  t('breasticles', 'nudity', 'en', 'high'),
  t('breasts', 'nudity', 'en', 'high'),
  t('brown showers', 'sexual', 'en', 'high'),
  t('brunette action', 'pornography', 'en', 'high'),
  t('buceta', 'nudity', 'en', 'high'),
  t('bukkake', 'pornography', 'en', 'high'),
  t('bullet vibe', 'sexual', 'en', 'high'),
  t('busty', 'nudity', 'en', 'high'),
  t('butt fuck', 'sexual', 'en', 'high'),
  t('buttfuck', 'sexual', 'en', 'high'),
  t('buttplug', 'sexual', 'en', 'high'),
  t('c*ck', 'nudity', 'en', 'high'),
  t('c*m', 'sexual', 'en', 'high'),
  t('c*nt', 'nudity', 'en', 'high'),
  t('c*nts', 'nudity', 'en', 'high'),
  t('c*um', 'sexual', 'en', 'high'),
  t('c0ck', 'nudity', 'en', 'high'),
  t('c0cks', 'nudity', 'en', 'high'),
  t('c0cksucked', 'sexual', 'en', 'high'),
  t('c0x', 'nudity', 'en', 'high'),
  t('camel toe', 'nudity', 'en', 'high'),
  t('cameltoe', 'nudity', 'en', 'high'),
  t('camgirl', 'pornography', 'en', 'high'),
  t('camslut', 'pornography', 'en', 'high'),
  t('camwhore', 'pornography', 'en', 'high'),
  t('cawk', 'nudity', 'en', 'high'),
  t('cawks', 'nudity', 'en', 'high'),
  t('cck', 'nudity', 'en', 'high'),
  t('chesticles', 'nudity', 'en', 'high'),
  t('choad', 'nudity', 'en', 'high'),
  t('choad nectar', 'sexual', 'en', 'high'),
  t('chocha', 'nudity', 'en', 'high'),
  t('chocolate rosebuds', 'sexual', 'en', 'high'),
  t('chode', 'nudity', 'en', 'high'),
  t('choke the chicken', 'sexual', 'en', 'high'),
  t('cl*t', 'nudity', 'en', 'high'),
  t('cl1t', 'nudity', 'en', 'high'),
  t('cleveland steamer', 'sexual', 'en', 'high'),
  t('clit', 'nudity', 'en', 'high'),
  t('clitoris', 'nudity', 'en', 'high'),
  t('clits', 'nudity', 'en', 'high'),
  t('clover clamps', 'sexual', 'en', 'high'),
  t('cnnt', 'nudity', 'en', 'high'),
  t('cnt', 'nudity', 'en', 'high'),
  t('cock droplets', 'sexual', 'en', 'high'),
  t('cock snot', 'sexual', 'en', 'high'),
  t('cock suck', 'sexual', 'en', 'high'),
  t('cock sucking', 'sexual', 'en', 'high'),
  t('cockskin', 'nudity', 'en', 'high'),
  t('cocksucc', 'sexual', 'en', 'high'),
  t('cocksuck', 'sexual', 'en', 'high'),
  t('cocksucked', 'sexual', 'en', 'high'),
  t('cocksucking', 'sexual', 'en', 'high'),
  t('cocksucks', 'sexual', 'en', 'high'),
  t('cocksuk', 'sexual', 'en', 'high'),
  t('cocsuck', 'sexual', 'en', 'high'),
  t('coochie', 'nudity', 'en', 'high'),
  t('coochy', 'nudity', 'en', 'high'),
  t('coot coot', 'nudity', 'en', 'high'),
  t('cooter', 'nudity', 'en', 'high'),
  t('cooter shooting', 'sexual', 'en', 'high'),
  t('cooterpuffing', 'sexual', 'en', 'high'),
  t('coprolagnia', 'sexual', 'en', 'high'),
  t('coprophilia', 'sexual', 'en', 'high'),
  t('creampie', 'pornography', 'en', 'high'),
  t('cum', 'sexual', 'en', 'high'),
  t('cum goon', 'sexual', 'en', 'high'),
  t('cumdump', 'sexual', 'en', 'high'),
  t('cumdumpster', 'sexual', 'en', 'high'),
  t('cumfreak', 'sexual', 'en', 'high'),
  t('cumguzzler', 'sexual', 'en', 'high'),
  t('cumhole', 'sexual', 'en', 'high'),
  t('cummer', 'sexual', 'en', 'high'),
  t('cumming', 'sexual', 'en', 'high'),
  t('cumrag', 'sexual', 'en', 'high'),
  t('cums', 'sexual', 'en', 'high'),
  t('cumshot', 'sexual', 'en', 'high'),
  t('cumshots', 'sexual', 'en', 'high'),
  t('cumslut', 'sexual', 'en', 'high'),
  t('cumsocket', 'sexual', 'en', 'high'),
  t('cumtart', 'sexual', 'en', 'high'),
  t('cumwagon', 'sexual', 'en', 'high'),
  t('cumz', 'sexual', 'en', 'high'),
  t('cunilingus', 'sexual', 'en', 'high'),
  t('cunillingus', 'sexual', 'en', 'high'),
  t('cunnie', 'nudity', 'en', 'high'),
  t('cunnilingus', 'sexual', 'en', 'high'),
  t('cunt', 'nudity', 'en', 'high'),
  t('cunt lick', 'sexual', 'en', 'high'),
  t('cunt lips', 'nudity', 'en', 'high'),
  t('cunthole', 'nudity', 'en', 'high'),
  t('cuntits', 'nudity', 'en', 'high'),
  t('cuntlick', 'sexual', 'en', 'high'),
  t('cuntlicking', 'sexual', 'en', 'high'),
  t('cunts', 'nudity', 'en', 'high'),
  t('cuntz', 'nudity', 'en', 'high'),
  t('cuunt', 'nudity', 'en', 'high'),
  t('cyberfck', 'sexual', 'en', 'high'),
  t('cyberfcks', 'sexual', 'en', 'high'),
  t('cyberfuc', 'sexual', 'en', 'high'),
  t('cyberfuccs', 'sexual', 'en', 'high'),
  t('cyberfuck', 'sexual', 'en', 'high'),
  t('cyberfucked', 'sexual', 'en', 'high'),
  t('cyberfucking', 'sexual', 'en', 'high'),
  t('cyberfucks', 'sexual', 'en', 'high'),
  t('cyberfucs', 'sexual', 'en', 'high'),
  t('cyberfukk', 'sexual', 'en', 'high'),
  t('cyberfukks', 'sexual', 'en', 'high'),
  t('cyberfvcks', 'sexual', 'en', 'high'),
  t('d!ck', 'nudity', 'en', 'high'),
  t('d!cks', 'nudity', 'en', 'high'),
  t('d!ld0', 'sexual', 'en', 'high'),
  t('d!ldo', 'sexual', 'en', 'high'),
  t('d*ck', 'nudity', 'en', 'high'),
  t('d*ldo', 'sexual', 'en', 'high'),
  t('d0ggy style', 'sexual', 'en', 'high'),
  t('d1ck', 'nudity', 'en', 'high'),
  t('d1cks', 'nudity', 'en', 'high'),
  t('d1ckz', 'nudity', 'en', 'high'),
  t('d1ldo', 'sexual', 'en', 'high'),
  t('date rape', 'sexual', 'en', 'high'),
  t('daterape', 'sexual', 'en', 'high'),
  t('dck', 'nudity', 'en', 'high'),
  t('deep throat', 'sexual', 'en', 'high'),
  t('deepthroat', 'sexual', 'en', 'high'),
  t('dendrophilia', 'sexual', 'en', 'high'),
  t('dickjuice', 'sexual', 'en', 'high'),
  t('dickmilk', 'sexual', 'en', 'high'),
  t('dickskin', 'nudity', 'en', 'high'),
  t('dickvag', 'nudity', 'en', 'high'),
  t('dickz', 'nudity', 'en', 'high'),
  t('diks', 'nudity', 'en', 'high'),
  t('dild0', 'sexual', 'en', 'high'),
  t('dildo', 'sexual', 'en', 'high'),
  t('dildos', 'sexual', 'en', 'high'),
  t('dirty pillows', 'nudity', 'en', 'high'),
  t('dirty sanchez', 'sexual', 'en', 'high'),
  t('dlck', 'nudity', 'en', 'high'),
  t('dlcks', 'nudity', 'en', 'high'),
  t('dog fuck', 'sexual', 'en', 'high'),
  t('dog fucking', 'sexual', 'en', 'high'),
  t('dog style', 'sexual', 'en', 'high'),
  t('doggie style', 'sexual', 'en', 'high'),
  t('doggiestyle', 'sexual', 'en', 'high'),
  t('doggin', 'sexual', 'en', 'high'),
  t('dogging', 'sexual', 'en', 'high'),
  t('doggo style', 'sexual', 'en', 'high'),
  t('doggy style', 'sexual', 'en', 'high'),
  t('doggy_style', 'sexual', 'en', 'high'),
  t('doggystyle', 'sexual', 'en', 'high'),
  t('dogie style', 'sexual', 'en', 'high'),
  t('dogstyle', 'sexual', 'en', 'high'),
  t('dolcett', 'pornography', 'en', 'high'),
  t('dominatrix', 'sexual', 'en', 'high'),
  t('dommes', 'sexual', 'en', 'high'),
  t('donkey punch', 'sexual', 'en', 'high'),
  t('donkeyribber', 'sexual', 'en', 'high'),
  t('double dick', 'sexual', 'en', 'high'),
  t('double dicking', 'sexual', 'en', 'high'),
  t('double dong', 'sexual', 'en', 'high'),
  t('double pen', 'sexual', 'en', 'high'),
  t('double penetration', 'sexual', 'en', 'high'),
  t('double-dong', 'sexual', 'en', 'high'),
  t('dp action', 'sexual', 'en', 'high'),
  t('dry hump', 'sexual', 'en', 'high'),
  t('dvda', 'pornography', 'en', 'high'),
  t('ecchi', 'pornography', 'en', 'high'),
  t('ejaculate', 'sexual', 'en', 'high'),
  t('ejaculated', 'sexual', 'en', 'high'),
  t('ejaculates', 'sexual', 'en', 'high'),
  t('ejaculating', 'sexual', 'en', 'high'),
  t('ejaculatings', 'sexual', 'en', 'high'),
  t('ejaculation', 'sexual', 'en', 'high'),
  t('ejakulate', 'sexual', 'en', 'high'),
  t('erectoplasm', 'sexual', 'en', 'high'),
  t('erotic', 'sexual', 'en', 'high'),
  t('erotism', 'sexual', 'en', 'high'),
  t('face fuck', 'sexual', 'en', 'high'),
  t('fannyflaps', 'nudity', 'en', 'high'),
  t('felatio', 'sexual', 'en', 'high'),
  t('felch', 'sexual', 'en', 'high'),
  t('felcher', 'sexual', 'en', 'high'),
  t('felching', 'sexual', 'en', 'high'),
  t('fellate', 'sexual', 'en', 'high'),
  t('fellatio', 'sexual', 'en', 'high'),
  t('fellatio aficionado', 'sexual', 'en', 'high'),
  t('fellator', 'sexual', 'en', 'high'),
  t('feltch', 'sexual', 'en', 'high'),
  t('female squirting', 'sexual', 'en', 'high'),
  t('femdom', 'pornography', 'en', 'high'),
  t('figging', 'sexual', 'en', 'high'),
  t('finger fuck', 'sexual', 'en', 'high'),
  t('fingerbang', 'sexual', 'en', 'high'),
  t('fingerbanged', 'sexual', 'en', 'high'),
  t('fingerfuck', 'sexual', 'en', 'high'),
  t('fingerfucked', 'sexual', 'en', 'high'),
  t('fingerfucker', 'sexual', 'en', 'high'),
  t('fingerfuckers', 'sexual', 'en', 'high'),
  t('fingerfucking', 'sexual', 'en', 'high'),
  t('fingerfucks', 'sexual', 'en', 'high'),
  t('fingerpop', 'sexual', 'en', 'high'),
  t('fistfuck', 'sexual', 'en', 'high'),
  t('fistfucked', 'sexual', 'en', 'high'),
  t('fistfucker', 'sexual', 'en', 'high'),
  t('fistfuckers', 'sexual', 'en', 'high'),
  t('fistfucking', 'sexual', 'en', 'high'),
  t('fistfuckings', 'sexual', 'en', 'high'),
  t('fistfucks', 'sexual', 'en', 'high'),
  t('fisting', 'sexual', 'en', 'high'),
  t('foot fetish', 'sexual', 'en', 'high'),
  t('footjob', 'sexual', 'en', 'high'),
  t('frotting', 'sexual', 'en', 'high'),
  t('fuckfest', 'sexual', 'en', 'high'),
  t('fuckhole', 'nudity', 'en', 'high'),
  t('fuckmachine', 'sexual', 'en', 'high'),
  t('fuckmeat', 'sexual', 'en', 'high'),
  t('fuckstar', 'pornography', 'en', 'high'),
  t('funbags', 'nudity', 'en', 'high'),
  t('futanari', 'pornography', 'en', 'high'),
  t('g-spot', 'nudity', 'en', 'high'),
  t('gang bang', 'sexual', 'en', 'high'),
  t('gangbang', 'sexual', 'en', 'high'),
  t('gangbanged', 'sexual', 'en', 'high'),
  t('gangbangs', 'sexual', 'en', 'high'),
  t('gay sex', 'sexual', 'en', 'high'),
  t('gaysex', 'sexual', 'en', 'high'),
  t('genitals', 'nudity', 'en', 'high'),
  t('giant cock', 'nudity', 'en', 'high'),
  t('girls gone wild', 'pornography', 'en', 'high'),
  t('girly bits', 'nudity', 'en', 'high'),
  t('goatcx', 'pornography', 'en', 'high'),
  t('goatse', 'pornography', 'en', 'high'),
  t('gokkun', 'pornography', 'en', 'high'),
  t('golden shower', 'sexual', 'en', 'high'),
  t('goo girl', 'pornography', 'en', 'high'),
  t('gooch', 'nudity', 'en', 'high'),
  t('goregasm', 'pornography', 'en', 'high'),
  t('grope', 'sexual', 'en', 'high'),
  t('groper', 'sexual', 'en', 'high'),
  t('group sex', 'sexual', 'en', 'high'),
  t('guro', 'pornography', 'en', 'high'),
  t('hand job', 'sexual', 'en', 'high'),
  t('handjob', 'sexual', 'en', 'high'),
  t('hardcoresex', 'pornography', 'en', 'high'),
  t('harry palms', 'sexual', 'en', 'high'),
  t('hentai', 'pornography', 'en', 'high'),
  t('homoerotic', 'sexual', 'en', 'high'),
  t('horniest', 'sexual', 'en', 'high'),
  t('horny', 'sexual', 'en', 'high'),
  t('hot carl', 'sexual', 'en', 'high'),
  t('hotsex', 'sexual', 'en', 'high'),
  t('humping', 'sexual', 'en', 'high'),
  t('incest', 'sexual', 'en', 'high'),
  t('intercourse', 'sexual', 'en', 'high'),
  t('j*ckoff', 'sexual', 'en', 'high'),
  t('j*sm', 'sexual', 'en', 'high'),
  t('j*zz', 'sexual', 'en', 'high'),
  t('j-offs', 'sexual', 'en', 'high'),
  t('ja!lbait', 'sexual', 'en', 'high'),
  t('ja1lbait', 'sexual', 'en', 'high'),
  t('jack off', 'sexual', 'en', 'high'),
  t('jack-off', 'sexual', 'en', 'high'),
  t('jack-offs', 'sexual', 'en', 'high'),
  t('jackoff', 'sexual', 'en', 'high'),
  t('jackoffs', 'sexual', 'en', 'high'),
  t('jackoffz', 'sexual', 'en', 'high'),
  t('jail bait', 'sexual', 'en', 'high'),
  t('jailba!t', 'sexual', 'en', 'high'),
  t('jailbait', 'sexual', 'en', 'high'),
  t('jerk off', 'sexual', 'en', 'high'),
  t('jerk-0ff', 'sexual', 'en', 'high'),
  t('jerk-0ffs', 'sexual', 'en', 'high'),
  t('jerk-off', 'sexual', 'en', 'high'),
  t('jerk-offs', 'sexual', 'en', 'high'),
  t('jerking off', 'sexual', 'en', 'high'),
  t('jerkoff', 'sexual', 'en', 'high'),
  t('jerkoff jerking off', 'sexual', 'en', 'high'),
  t('jerkoffs', 'sexual', 'en', 'high'),
  t('jerks off', 'sexual', 'en', 'high'),
  t('jism', 'sexual', 'en', 'high'),
  t('jiz', 'sexual', 'en', 'high'),
  t('jizm', 'sexual', 'en', 'high'),
  t('jizz', 'sexual', 'en', 'high'),
  t('jizz eater', 'sexual', 'en', 'high'),
  t('jizz licker', 'sexual', 'en', 'high'),
  t('jizz-jockey', 'sexual', 'en', 'high'),
  t('jizzed', 'sexual', 'en', 'high'),
  t('jizzes', 'sexual', 'en', 'high'),
  t('jizzing', 'sexual', 'en', 'high'),
  t('juggs', 'nudity', 'en', 'high'),
  t('k*ock', 'nudity', 'en', 'high'),
  t('kawk', 'nudity', 'en', 'high'),
  t('kid diddler', 'sexual', 'en', 'high'),
  t('kiddy touch', 'sexual', 'en', 'high'),
  t('kinbaku', 'sexual', 'en', 'high'),
  t('kinkster', 'sexual', 'en', 'high'),
  t('kiunt', 'nudity', 'en', 'high'),
  t('klitoris', 'nudity', 'en', 'high'),
  t('knobbing', 'sexual', 'en', 'high'),
  t('knt', 'nudity', 'en', 'high'),
  t('kock', 'nudity', 'en', 'high'),
  t('kooch', 'nudity', 'en', 'high'),
  t('kootch', 'nudity', 'en', 'high'),
  t('kumer', 'sexual', 'en', 'high'),
  t('kummer', 'sexual', 'en', 'high'),
  t('kumming', 'sexual', 'en', 'high'),
  t('kums', 'sexual', 'en', 'high'),
  t('kunilingus', 'sexual', 'en', 'high'),
  t('kunt', 'nudity', 'en', 'high'),
  t('l*mp d*ck', 'nudity', 'en', 'high'),
  t('l@dyb0i', 'pornography', 'en', 'high'),
  t('l@dyb0y', 'pornography', 'en', 'high'),
  t('l@dyboy', 'pornography', 'en', 'high'),
  t('labia', 'nudity', 'en', 'high'),
  t('ladboys', 'pornography', 'en', 'high'),
  t('ladboyz', 'pornography', 'en', 'high'),
  t('ladiboy', 'pornography', 'en', 'high'),
  t('lady-boy', 'pornography', 'en', 'high'),
  t('ladyb0i', 'pornography', 'en', 'high'),
  t('ladyb0y', 'pornography', 'en', 'high'),
  t('ladyboy', 'pornography', 'en', 'high'),
  t('ladyboys', 'pornography', 'en', 'high'),
  t('ladyboyz', 'pornography', 'en', 'high'),
  t('leather restraint', 'sexual', 'en', 'high'),
  t('leather straight jacket', 'sexual', 'en', 'high'),
  t('lemon party', 'pornography', 'en', 'high'),
  t('limp dick', 'nudity', 'en', 'high'),
  t('livesex', 'pornography', 'en', 'high'),
  t('lolita', 'sexual', 'en', 'high'),
  t('lovemaking', 'sexual', 'en', 'high'),
  t('m45terbate', 'sexual', 'en', 'high'),
  t('m@asterbated', 'sexual', 'en', 'high'),
  t('ma5terb8', 'sexual', 'en', 'high'),
  t('ma5terbate', 'sexual', 'en', 'high'),
  t('make me come', 'sexual', 'en', 'high'),
  t('male squirting', 'sexual', 'en', 'high'),
  t('manseed', 'sexual', 'en', 'high'),
  t('master-bate', 'sexual', 'en', 'high'),
  t('masterb8', 'sexual', 'en', 'high'),
  t('masterbat*', 'sexual', 'en', 'high'),
  t('masterbat3', 'sexual', 'en', 'high'),
  t('masterbate', 'sexual', 'en', 'high'),
  t('masterbation', 'sexual', 'en', 'high'),
  t('masterbations', 'sexual', 'en', 'high'),
  t('masturbate', 'sexual', 'en', 'high'),
  t('masturbating', 'sexual', 'en', 'high'),
  t('masturbation', 'sexual', 'en', 'high'),
  t('meat curtains', 'nudity', 'en', 'high'),
  t('meat-sword', 'nudity', 'en', 'high'),
  t('menage a trois', 'sexual', 'en', 'high'),
  t('milf', 'pornography', 'en', 'high'),
  t('minge', 'nudity', 'en', 'high'),
  t('missionary position', 'sexual', 'en', 'high'),
  t('molester', 'sexual', 'en', 'high'),
  t('mound of venus', 'nudity', 'en', 'high'),
  t('mr hands', 'pornography', 'en', 'high'),
  t('muff diver', 'sexual', 'en', 'high'),
  t('muffdiver', 'sexual', 'en', 'high'),
  t('muffdiving', 'sexual', 'en', 'high'),
  t('nambla', 'sexual', 'en', 'high'),
  t('nawashi', 'sexual', 'en', 'high'),
  t('nimphomania', 'sexual', 'en', 'high'),
  t('nipple', 'nudity', 'en', 'high'),
  t('nipples', 'nudity', 'en', 'high'),
  t('nsfw', 'pornography', 'en', 'high'),
  t('nsfw images', 'pornography', 'en', 'high'),
  t('nude', 'nudity', 'en', 'high'),
  t('nudity', 'nudity', 'en', 'high'),
  t('nutsack', 'nudity', 'en', 'high'),
  t('nutsacks', 'nudity', 'en', 'high'),
  t('nympho', 'sexual', 'en', 'high'),
  t('nymphomania', 'sexual', 'en', 'high'),
  t('nymphomaniac', 'sexual', 'en', 'high'),
  t('omorashi', 'sexual', 'en', 'high'),
  t('one cup two girls', 'pornography', 'en', 'high'),
  t('one guy one jar', 'pornography', 'en', 'high'),
  t('orgasim', 'sexual', 'en', 'high'),
  t('orgasims', 'sexual', 'en', 'high'),
  t('orgasm', 'sexual', 'en', 'high'),
  t('orgasms', 'sexual', 'en', 'high'),
  t('orgy', 'sexual', 'en', 'high'),
  t('p*rn', 'pornography', 'en', 'high'),
  t('p*ssflaps', 'nudity', 'en', 'high'),
  t('p*ssy', 'nudity', 'en', 'high'),
  t('p0rn', 'pornography', 'en', 'high'),
  t('p3nisfcker', 'sexual', 'en', 'high'),
  t('p3nisfcukers', 'sexual', 'en', 'high'),
  t('p3nisfvcker', 'sexual', 'en', 'high'),
  t('p3nisfvckers', 'sexual', 'en', 'high'),
  t('paedophile', 'sexual', 'en', 'high'),
  t('palm jockey', 'sexual', 'en', 'high'),
  t('panooch', 'nudity', 'en', 'high'),
  t('pecker', 'nudity', 'en', 'high'),
  t('pedo', 'sexual', 'en', 'high'),
  t('pedobear', 'sexual', 'en', 'high'),
  t('pedobears', 'sexual', 'en', 'high'),
  t('pedophile', 'sexual', 'en', 'high'),
  t('pedophl', 'sexual', 'en', 'high'),
  t('pedos', 'sexual', 'en', 'high'),
  t('pedoz', 'sexual', 'en', 'high'),
  t('peener', 'nudity', 'en', 'high'),
  t('pegging', 'sexual', 'en', 'high'),
  t('penis', 'nudity', 'en', 'high'),
  t('penisfcker', 'sexual', 'en', 'high'),
  t('penisfuccer', 'sexual', 'en', 'high'),
  t('penisfucker', 'sexual', 'en', 'high'),
  t('penisfuckers', 'sexual', 'en', 'high'),
  t('penisfvcker', 'sexual', 'en', 'high'),
  t('penisfvckers', 'sexual', 'en', 'high'),
  t('phone sex', 'sexual', 'en', 'high'),
  t('phonesex', 'sexual', 'en', 'high'),
  t('pimpis', 'nudity', 'en', 'high'),
  t('piss pig', 'sexual', 'en', 'high'),
  t('pissflap', 'nudity', 'en', 'high'),
  t('pissflaps', 'nudity', 'en', 'high'),
  t('pisspig', 'sexual', 'en', 'high'),
  t('ponyplay', 'sexual', 'en', 'high'),
  t('poon', 'nudity', 'en', 'high'),
  t('poonani', 'nudity', 'en', 'high'),
  t('poonany', 'nudity', 'en', 'high'),
  t('poontang', 'nudity', 'en', 'high'),
  t('porn', 'pornography', 'en', 'high'),
  t('porno', 'pornography', 'en', 'high'),
  t('pornography', 'pornography', 'en', 'high'),
  t('pornos', 'pornography', 'en', 'high'),
  t('prince albert piercing', 'nudity', 'en', 'high'),
  t('pron', 'pornography', 'en', 'high'),
  t('pssy', 'nudity', 'en', 'high'),
  t('pthc', 'sexual', 'en', 'high'),
  t('pu$sy', 'nudity', 'en', 'high'),
  t('pu55y', 'nudity', 'en', 'high'),
  t('pube', 'nudity', 'en', 'high'),
  t('pubes', 'nudity', 'en', 'high'),
  t('pull the pud', 'sexual', 'en', 'high'),
  t('punani', 'nudity', 'en', 'high'),
  t('punanny', 'nudity', 'en', 'high'),
  t('punany', 'nudity', 'en', 'high'),
  t('pusies', 'nudity', 'en', 'high'),
  t('pusse', 'nudity', 'en', 'high'),
  t('pusses', 'nudity', 'en', 'high'),
  t('pussi', 'nudity', 'en', 'high'),
  t('pussie', 'nudity', 'en', 'high'),
  t('pussies', 'nudity', 'en', 'high'),
  t('pusslicker', 'sexual', 'en', 'high'),
  t('pussy', 'nudity', 'en', 'high'),
  t('pussy fucker', 'sexual', 'en', 'high'),
  t('pussy lick', 'sexual', 'en', 'high'),
  t('pussy licker', 'sexual', 'en', 'high'),
  t('pussy licking', 'sexual', 'en', 'high'),
  t('pussylickers', 'sexual', 'en', 'high'),
  t('pussylicking', 'sexual', 'en', 'high'),
  t('pussys', 'nudity', 'en', 'high'),
  t('pusy', 'nudity', 'en', 'high'),
  t('puussy', 'nudity', 'en', 'high'),
  t('puzzies', 'nudity', 'en', 'high'),
  t('puzzy', 'nudity', 'en', 'high'),
  t('quim', 'nudity', 'en', 'high'),
  t('raging boner', 'nudity', 'en', 'high'),
  t('rap3', 'sexual', 'en', 'high'),
  t('rap3d', 'sexual', 'en', 'high'),
  t('rape', 'sexual', 'en', 'high'),
  t('raped', 'sexual', 'en', 'high'),
  t('raping', 'sexual', 'en', 'high'),
  t('rapist', 'sexual', 'en', 'high'),
  t('reacharound', 'sexual', 'en', 'high'),
  t('rectum', 'nudity', 'en', 'high'),
  t('renob', 'nudity', 'en', 'high'),
  t('reverse cowgirl', 'sexual', 'en', 'high'),
  t('rim job', 'sexual', 'en', 'high'),
  t('rimjaw', 'sexual', 'en', 'high'),
  t('rimjob', 'sexual', 'en', 'high'),
  t('rimming', 'sexual', 'en', 'high'),
  t('rosy palm', 'sexual', 'en', 'high'),
  t('rosy palm and her 5 sisters', 'sexual', 'en', 'high'),
  t('rusty trombone', 'sexual', 'en', 'high'),
  t('s&m', 'sexual', 'en', 'high'),
  t('schlong', 'nudity', 'en', 'high'),
  t('scissoring', 'sexual', 'en', 'high'),
  t('scroat', 'nudity', 'en', 'high'),
  t('scrote', 'nudity', 'en', 'high'),
  t('scrotum', 'nudity', 'en', 'high'),
  t('semen', 'sexual', 'en', 'high'),
  t('sex', 'sexual', 'en', 'high'),
  t('sexcam', 'pornography', 'en', 'high'),
  t('sexo', 'sexual', 'en', 'high'),
  t('sexual', 'sexual', 'en', 'high'),
  t('sexually', 'sexual', 'en', 'high'),
  t('sh3mal3', 'pornography', 'en', 'high'),
  t('sh3male', 'pornography', 'en', 'high'),
  t('shagger', 'sexual', 'en', 'high'),
  t('shaggin', 'sexual', 'en', 'high'),
  t('shagging', 'sexual', 'en', 'high'),
  t('shaved beaver', 'nudity', 'en', 'high'),
  t('shaved pussy', 'nudity', 'en', 'high'),
  t('she-male', 'pornography', 'en', 'high'),
  t('shemal3', 'pornography', 'en', 'high'),
  t('shemale', 'pornography', 'en', 'high'),
  t('shemales', 'pornography', 'en', 'high'),
  t('shibari', 'sexual', 'en', 'high'),
  t('shlong', 'nudity', 'en', 'high'),
  t('shmale', 'pornography', 'en', 'high'),
  t('shota', 'sexual', 'en', 'high'),
  t('smut', 'pornography', 'en', 'high'),
  t('snatch licker', 'sexual', 'en', 'high'),
  t('sodomize', 'sexual', 'en', 'high'),
  t('sodomy', 'sexual', 'en', 'high'),
  t('sp*nk', 'sexual', 'en', 'high'),
  t('spanking', 'sexual', 'en', 'high'),
  t('sphincter', 'nudity', 'en', 'high'),
  t('splooge', 'sexual', 'en', 'high'),
  t('splooge moose', 'sexual', 'en', 'high'),
  t('spooge', 'sexual', 'en', 'high'),
  t('strapon', 'sexual', 'en', 'high'),
  t('strappado', 'sexual', 'en', 'high'),
  t('strip club', 'sexual', 'en', 'high'),
  t('style doggy', 'sexual', 'en', 'high'),
  t('suck my cock', 'sexual', 'en', 'high'),
  t('suck my d', 'sexual', 'en', 'high'),
  t('suck my dick', 'sexual', 'en', 'high'),
  t('suck off', 'sexual', 'en', 'high'),
  t('suicide girls', 'pornography', 'en', 'high'),
  t('swinger', 'sexual', 'en', 'high'),
  t('t*t', 'nudity', 'en', 'high'),
  t('t*tty', 'nudity', 'en', 'high'),
  t('t1tt1e5', 'nudity', 'en', 'high'),
  t('t1tties', 'nudity', 'en', 'high'),
  t('tadger', 'nudity', 'en', 'high'),
  t('tallywacker', 'nudity', 'en', 'high'),
  t('tea bagging', 'sexual', 'en', 'high'),
  t('teets', 'nudity', 'en', 'high'),
  t('testical', 'nudity', 'en', 'high'),
  t('testicle', 'nudity', 'en', 'high'),
  t('throat yogurt', 'sexual', 'en', 'high'),
  t('throater', 'sexual', 'en', 'high'),
  t('throating', 'sexual', 'en', 'high'),
  t('thumbzilla', 'pornography', 'en', 'high'),
  t('tickle the pickle', 'sexual', 'en', 'high'),
  t('titfuck', 'sexual', 'en', 'high'),
  t('tits', 'nudity', 'en', 'high'),
  t('titt', 'nudity', 'en', 'high'),
  t('tittie5', 'nudity', 'en', 'high'),
  t('tittiefucker', 'sexual', 'en', 'high'),
  t('titties', 'nudity', 'en', 'high'),
  t('titty', 'nudity', 'en', 'high'),
  t('tittyfuck', 'sexual', 'en', 'high'),
  t('tittywank', 'sexual', 'en', 'high'),
  t('titwank', 'sexual', 'en', 'high'),
  t('tongue in a', 'sexual', 'en', 'high'),
  t('topless', 'nudity', 'en', 'high'),
  t('tribadism', 'sexual', 'en', 'high'),
  t('trouser snake', 'nudity', 'en', 'high'),
  t('trousersnake', 'nudity', 'en', 'high'),
  t('tub girl', 'pornography', 'en', 'high'),
  t('tubgirl', 'pornography', 'en', 'high'),
  t('two girls one cup', 'pornography', 'en', 'high'),
  t('undressing', 'nudity', 'en', 'high'),
  t('upskirt', 'pornography', 'en', 'high'),
  t('upskirts', 'pornography', 'en', 'high'),
  t('urethra play', 'sexual', 'en', 'high'),
  t('urophilia', 'sexual', 'en', 'high'),
  t('va-j-j', 'nudity', 'en', 'high'),
  t('vag', 'nudity', 'en', 'high'),
  t('vagina', 'nudity', 'en', 'high'),
  t('vajayjay', 'nudity', 'en', 'high'),
  t('venus mound', 'nudity', 'en', 'high'),
  t('vibrator', 'sexual', 'en', 'high'),
  t('violet wand', 'sexual', 'en', 'high'),
  t('vjayjay', 'nudity', 'en', 'high'),
  t('vorarephilia', 'sexual', 'en', 'high'),
  t('voyeurweb', 'pornography', 'en', 'high'),
  t('voyuer', 'sexual', 'en', 'high'),
  t('vulva', 'nudity', 'en', 'high'),
  t('w*nk', 'sexual', 'en', 'high'),
  t('wang wrangler', 'sexual', 'en', 'high'),
  t('wank', 'sexual', 'en', 'high'),
  t('wank off', 'sexual', 'en', 'high'),
  t('wanked', 'sexual', 'en', 'high'),
  t('wanking', 'sexual', 'en', 'high'),
  t('wanks', 'sexual', 'en', 'high'),
  t('wet dream', 'sexual', 'en', 'high'),
  t('whack off', 'sexual', 'en', 'high'),
  t('willy-whacker', 'sexual', 'en', 'high'),
  t('worldsex', 'pornography', 'en', 'high'),
  t('wrinkled starfish', 'nudity', 'en', 'high'),
  t('xrated', 'pornography', 'en', 'high'),
  t('xxx', 'pornography', 'en', 'high'),
  t('yaoi', 'pornography', 'en', 'high'),
  t('yellow showers', 'sexual', 'en', 'high'),
  t('yiffy', 'pornography', 'en', 'high'),
  t('zoophilia', 'sexual', 'en', 'high'),

  // ── ar (17 terms)
  t('احتلام', 'sexual', 'ar', 'high'),
  t('اغتصاب', 'sexual', 'ar', 'high'),
  t('بز', 'nudity', 'ar', 'high'),
  t('بزاز', 'nudity', 'ar', 'high'),
  t('بظر', 'nudity', 'ar', 'high'),
  t('بيضان', 'nudity', 'ar', 'high'),
  t('تمص', 'sexual', 'ar', 'high'),
  t('ثدي', 'nudity', 'ar', 'high'),
  t('جماع', 'sexual', 'ar', 'high'),
  t('حلمة', 'nudity', 'ar', 'high'),
  t('زب', 'nudity', 'ar', 'high'),
  t('سحاق', 'sexual', 'ar', 'high'),
  t('سكس', 'sexual', 'ar', 'high'),
  t('شرج', 'nudity', 'ar', 'high'),
  t('كس', 'nudity', 'ar', 'high'),
  t('لواط', 'sexual', 'ar', 'high'),
  t('نيك', 'sexual', 'ar', 'high'),

  // ── bn (6 terms)
  t('চোদা', 'sexual', 'bn', 'high'),
  t('চোদা চোদি', 'sexual', 'bn', 'high'),
  t('চোদা মেয়ে', 'sexual', 'bn', 'high'),
  t('চোদা হোর', 'sexual', 'bn', 'high'),
  t('পোদ মারা', 'sexual', 'bn', 'high'),
  t('মেয়ের পুটকি', 'nudity', 'bn', 'high'),

  // ── de (22 terms)
  t('bumsen', 'sexual', 'de', 'high'),
  t('fick', 'sexual', 'de', 'high'),
  t('ficken', 'sexual', 'de', 'high'),
  t('fotze', 'nudity', 'de', 'high'),
  t('gefickt', 'sexual', 'de', 'high'),
  t('morgenlatte', 'nudity', 'de', 'high'),
  t('muschi', 'nudity', 'de', 'high'),
  t('möpse', 'nudity', 'de', 'high'),
  t('möse', 'nudity', 'de', 'high'),
  t('nackt', 'nudity', 'de', 'high'),
  t('nippel', 'nudity', 'de', 'high'),
  t('onanieren', 'sexual', 'de', 'high'),
  t('orgasmus', 'sexual', 'de', 'high'),
  t('pimmel', 'nudity', 'de', 'high'),
  t('pimpern', 'sexual', 'de', 'high'),
  t('schnackeln', 'sexual', 'de', 'high'),
  t('schwanz', 'nudity', 'de', 'high'),
  t('tittchen', 'nudity', 'de', 'high'),
  t('titten', 'nudity', 'de', 'high'),
  t('vögeln', 'sexual', 'de', 'high'),
  t('wichse', 'sexual', 'de', 'high'),
  t('wichsen', 'sexual', 'de', 'high'),

  // ── es (19 terms)
  t('chucha', 'nudity', 'es', 'high'),
  t('coprofagía', 'sexual', 'es', 'high'),
  t('coño', 'nudity', 'es', 'high'),
  t('culeada', 'sexual', 'es', 'high'),
  t('culear', 'sexual', 'es', 'high'),
  t('esperma', 'sexual', 'es', 'high'),
  t('follador', 'sexual', 'es', 'high'),
  t('follar', 'sexual', 'es', 'high'),
  t('hacer una paja', 'sexual', 'es', 'high'),
  t('haciendo el amor', 'sexual', 'es', 'high'),
  t('mamada', 'sexual', 'es', 'high'),
  t('panocha', 'nudity', 'es', 'high'),
  t('pezón', 'nudity', 'es', 'high'),
  t('polla', 'nudity', 'es', 'high'),
  t('prostituta', 'sexual', 'es', 'high'),
  t('ramera', 'sexual', 'es', 'high'),
  t('sexo oral', 'sexual', 'es', 'high'),
  t('tetas grandes', 'nudity', 'es', 'high'),
  t('verga', 'nudity', 'es', 'high'),

  // ── fr (19 terms)
  t('bander', 'sexual', 'fr', 'high'),
  t('brackmard', 'nudity', 'fr', 'high'),
  t('branlage', 'sexual', 'fr', 'high'),
  t('branler', 'sexual', 'fr', 'high'),
  t('branlette', 'sexual', 'fr', 'high'),
  t('brouter le cresson', 'sexual', 'fr', 'high'),
  t('clito', 'nudity', 'fr', 'high'),
  t('cramouille', 'nudity', 'fr', 'high'),
  t('enculer', 'sexual', 'fr', 'high'),
  t('jouir', 'sexual', 'fr', 'high'),
  t('ménage à trois', 'sexual', 'fr', 'high'),
  t('palucher', 'sexual', 'fr', 'high'),
  t('teuch', 'nudity', 'fr', 'high'),
  t('tringler', 'sexual', 'fr', 'high'),
  t('trique', 'nudity', 'fr', 'high'),
  t('troncher', 'sexual', 'fr', 'high'),
  t('turlute', 'sexual', 'fr', 'high'),
  t('zigounette', 'nudity', 'fr', 'high'),
  t('zizi', 'nudity', 'fr', 'high'),

  // ── hi (33 terms)
  t('aand', 'nudity', 'hi', 'high'),
  t('balatkar', 'sexual', 'hi', 'high'),
  t('balatkari', 'sexual', 'hi', 'high'),
  t('bhosad', 'nudity', 'hi', 'high'),
  t('boobe', 'nudity', 'hi', 'high'),
  t('chod', 'sexual', 'hi', 'high'),
  t('chooche', 'nudity', 'hi', 'high'),
  t('choochi', 'nudity', 'hi', 'high'),
  t('choot', 'nudity', 'hi', 'high'),
  t('chuche', 'nudity', 'hi', 'high'),
  t('chuchi', 'nudity', 'hi', 'high'),
  t('chudaap', 'sexual', 'hi', 'high'),
  t('chudai khanaa', 'sexual', 'hi', 'high'),
  t('chudam chudai', 'sexual', 'hi', 'high'),
  t('chude', 'sexual', 'hi', 'high'),
  t('chut', 'nudity', 'hi', 'high'),
  t('chut maarli', 'sexual', 'hi', 'high'),
  t('chutan', 'nudity', 'hi', 'high'),
  t('jhant', 'nudity', 'hi', 'high'),
  t('loda', 'nudity', 'hi', 'high'),
  t('lund choos', 'sexual', 'hi', 'high'),
  t('mooh mein le', 'sexual', 'hi', 'high'),
  t('mutth', 'sexual', 'hi', 'high'),
  t('tatte', 'nudity', 'hi', 'high'),
  t('गांडमारना', 'sexual', 'hi', 'high'),
  t('चूत', 'nudity', 'hi', 'high'),
  t('चोद', 'sexual', 'hi', 'high'),
  t('मुँह में ले', 'sexual', 'hi', 'high'),
  t('लवड़ा', 'nudity', 'hi', 'high'),
  t('लावड़ा', 'nudity', 'hi', 'high'),
  t('लावडा', 'nudity', 'hi', 'high'),
  t('लुंड', 'nudity', 'hi', 'high'),
  t('लौड़ा', 'nudity', 'hi', 'high'),

  // ── it (32 terms)
  t('ammucchiata', 'sexual', 'it', 'high'),
  t('anale', 'sexual', 'it', 'high'),
  t('bocchinara', 'sexual', 'it', 'high'),
  t('bocchino', 'sexual', 'it', 'high'),
  t('caciocappella', 'nudity', 'it', 'high'),
  t('chiavare', 'sexual', 'it', 'high'),
  t('chiavata', 'sexual', 'it', 'high'),
  t('ciucciami il cazzo', 'sexual', 'it', 'high'),
  t('ditalino', 'sexual', 'it', 'high'),
  t('fottere', 'sexual', 'it', 'high'),
  t('fregna', 'nudity', 'it', 'high'),
  t('guardone', 'sexual', 'it', 'high'),
  t('ingoio', 'sexual', 'it', 'high'),
  t('nerchia', 'nudity', 'it', 'high'),
  t('patonza', 'nudity', 'it', 'high'),
  t('pecorina', 'sexual', 'it', 'high'),
  t('pincare', 'sexual', 'it', 'high'),
  t('pompino', 'sexual', 'it', 'high'),
  t('potta', 'nudity', 'it', 'high'),
  t('sborra', 'sexual', 'it', 'high'),
  t('sborrata', 'sexual', 'it', 'high'),
  t('scopare', 'sexual', 'it', 'high'),
  t('scopata', 'sexual', 'it', 'high'),
  t('sorca', 'nudity', 'it', 'high'),
  t('spompinare', 'sexual', 'it', 'high'),
  t('sticchio', 'nudity', 'it', 'high'),
  t('sveltina', 'sexual', 'it', 'high'),
  t('sverginare', 'sexual', 'it', 'high'),
  t('tette', 'nudity', 'it', 'high'),
  t('topa', 'nudity', 'it', 'high'),
  t('trombare', 'sexual', 'it', 'high'),
  t('zinne', 'nudity', 'it', 'high'),

  // ── ja (105 terms)
  t('g スポット', 'sexual', 'ja', 'high'),
  t('s ＆ m', 'sexual', 'ja', 'high'),
  t('sm女王', 'sexual', 'ja', 'high'),
  t('おしりのあな', 'nudity', 'ja', 'high'),
  t('おっぱい', 'nudity', 'ja', 'high'),
  t('ちんこ', 'nudity', 'ja', 'high'),
  t('ちんちん', 'nudity', 'ja', 'high'),
  t('ふたなり', 'pornography', 'ja', 'high'),
  t('ぶっかけ', 'pornography', 'ja', 'high'),
  t('まんこ', 'nudity', 'ja', 'high'),
  t('やおい', 'pornography', 'ja', 'high'),
  t('アナリングス', 'sexual', 'ja', 'high'),
  t('アナル', 'sexual', 'ja', 'high'),
  t('イラマチオ', 'sexual', 'ja', 'high'),
  t('エッチ', 'sexual', 'ja', 'high'),
  t('エロ', 'pornography', 'ja', 'high'),
  t('エロティズム', 'sexual', 'ja', 'high'),
  t('エロティック', 'sexual', 'ja', 'high'),
  t('オッパイ', 'nudity', 'ja', 'high'),
  t('オナニー', 'sexual', 'ja', 'high'),
  t('オマンコ', 'nudity', 'ja', 'high'),
  t('オーガズム', 'sexual', 'ja', 'high'),
  t('カーマスートラ', 'sexual', 'ja', 'high'),
  t('クリトリス', 'nudity', 'ja', 'high'),
  t('クンニリングス', 'sexual', 'ja', 'high'),
  t('グループ・セックス', 'sexual', 'ja', 'high'),
  t('ゲイ・セックス', 'sexual', 'ja', 'high'),
  t('ゴックン', 'pornography', 'ja', 'high'),
  t('ゴールデンシャワー', 'sexual', 'ja', 'high'),
  t('サディズム', 'sexual', 'ja', 'high'),
  t('スウィンガー', 'sexual', 'ja', 'high'),
  t('スカトロ', 'pornography', 'ja', 'high'),
  t('スカートの中', 'sexual', 'ja', 'high'),
  t('ストラップオン', 'sexual', 'ja', 'high'),
  t('ストリップ劇場', 'nudity', 'ja', 'high'),
  t('セクシーな 10 代', 'sexual', 'ja', 'high'),
  t('セックス', 'sexual', 'ja', 'high'),
  t('ソドミー', 'sexual', 'ja', 'high'),
  t('テレフォンセックス', 'sexual', 'ja', 'high'),
  t('ディルド', 'sexual', 'ja', 'high'),
  t('ディープ・スロート', 'sexual', 'ja', 'high'),
  t('デートレイプ', 'sexual', 'ja', 'high'),
  t('トップレス', 'nudity', 'ja', 'high'),
  t('ドッグスタイル', 'sexual', 'ja', 'high'),
  t('ヌード', 'nudity', 'ja', 'high'),
  t('バイブレーター', 'sexual', 'ja', 'high'),
  t('バック・スタイル', 'sexual', 'ja', 'high'),
  t('パイパン', 'nudity', 'ja', 'high'),
  t('フェティッシュ', 'sexual', 'ja', 'high'),
  t('フェラチオ', 'sexual', 'ja', 'high'),
  t('プリンス アルバート ピアス', 'nudity', 'ja', 'high'),
  t('ベアバック', 'pornography', 'ja', 'high'),
  t('ペニス', 'nudity', 'ja', 'high'),
  t('ペニスバンド', 'sexual', 'ja', 'high'),
  t('ボンテージ', 'sexual', 'ja', 'high'),
  t('ボールギャグ', 'sexual', 'ja', 'high'),
  t('ポルノ', 'pornography', 'ja', 'high'),
  t('ポルノグラフィー', 'pornography', 'ja', 'high'),
  t('マスターベーション', 'sexual', 'ja', 'high'),
  t('レイプ', 'sexual', 'ja', 'high'),
  t('ロリータ', 'sexual', 'ja', 'high'),
  t('中出し', 'pornography', 'ja', 'high'),
  t('乱交', 'sexual', 'ja', 'high'),
  t('乳首', 'nudity', 'ja', 'high'),
  t('二穴', 'pornography', 'ja', 'high'),
  t('児童性虐待', 'sexual', 'ja', 'high'),
  t('剃毛', 'nudity', 'ja', 'high'),
  t('勃起する', 'sexual', 'ja', 'high'),
  t('合意の性交', 'sexual', 'ja', 'high'),
  t('売春婦', 'sexual', 'ja', 'high'),
  t('夢精', 'sexual', 'ja', 'high'),
  t('大陰唇', 'nudity', 'ja', 'high'),
  t('射精', 'sexual', 'ja', 'high'),
  t('尿道プレイ', 'sexual', 'ja', 'high'),
  t('巨乳', 'nudity', 'ja', 'high'),
  t('巨根', 'nudity', 'ja', 'high'),
  t('幼児性愛者', 'sexual', 'ja', 'high'),
  t('強姦犯', 'sexual', 'ja', 'high'),
  t('後背位', 'sexual', 'ja', 'high'),
  t('性交', 'sexual', 'ja', 'high'),
  t('手コキ', 'sexual', 'ja', 'high'),
  t('新しいポルノ', 'pornography', 'ja', 'high'),
  t('正常位', 'sexual', 'ja', 'high'),
  t('淫乱', 'sexual', 'ja', 'high'),
  t('潮吹き女', 'sexual', 'ja', 'high'),
  t('潮吹き男性', 'sexual', 'ja', 'high'),
  t('獣姦', 'sexual', 'ja', 'high'),
  t('玉なめ', 'sexual', 'ja', 'high'),
  t('玉舐め', 'sexual', 'ja', 'high'),
  t('生殖器', 'nudity', 'ja', 'high'),
  t('精液', 'sexual', 'ja', 'high'),
  t('糞尿愛好症', 'sexual', 'ja', 'high'),
  t('緊縛', 'sexual', 'ja', 'high'),
  t('肛門', 'nudity', 'ja', 'high'),
  t('膣', 'nudity', 'ja', 'high'),
  t('茶色のシャワー', 'sexual', 'ja', 'high'),
  t('裸の女性', 'nudity', 'ja', 'high'),
  t('覗き', 'sexual', 'ja', 'high'),
  t('貞操帯', 'sexual', 'ja', 'high'),
  t('足フェチ', 'sexual', 'ja', 'high'),
  t('輪姦', 'sexual', 'ja', 'high'),
  t('近親相姦', 'sexual', 'ja', 'high'),
  t('陰毛', 'nudity', 'ja', 'high'),
  t('革抑制', 'sexual', 'ja', 'high'),
  t('騎上位', 'sexual', 'ja', 'high'),

  // ── ko (25 terms)
  t('강간', 'sexual', 'ko', 'high'),
  t('거유', 'nudity', 'ko', 'high'),
  t('근친', 'sexual', 'ko', 'high'),
  t('딸딸이', 'sexual', 'ko', 'high'),
  t('로리타', 'sexual', 'ko', 'high'),
  t('망가', 'pornography', 'ko', 'high'),
  t('몰카', 'sexual', 'ko', 'high'),
  t('바바리맨', 'nudity', 'ko', 'high'),
  t('보지', 'nudity', 'ko', 'high'),
  t('불알', 'nudity', 'ko', 'high'),
  t('빠구리', 'sexual', 'ko', 'high'),
  t('사까시', 'sexual', 'ko', 'high'),
  t('섹스', 'sexual', 'ko', 'high'),
  t('스와핑', 'sexual', 'ko', 'high'),
  t('씹물', 'sexual', 'ko', 'high'),
  t('야동', 'pornography', 'ko', 'high'),
  t('야사', 'pornography', 'ko', 'high'),
  t('야애니', 'pornography', 'ko', 'high'),
  t('에로', 'pornography', 'ko', 'high'),
  t('은꼴', 'pornography', 'ko', 'high'),
  t('자위', 'sexual', 'ko', 'high'),
  t('자지', 'nudity', 'ko', 'high'),
  t('창녀', 'sexual', 'ko', 'high'),
  t('포르노', 'pornography', 'ko', 'high'),
  t('후장', 'nudity', 'ko', 'high'),

  // ── nl (35 terms)
  t('afberen', 'sexual', 'nl', 'high'),
  t('afrukken', 'sexual', 'nl', 'high'),
  t('afwerkplaats', 'sexual', 'nl', 'high'),
  t('afzuigen', 'sexual', 'nl', 'high'),
  t('beffen', 'sexual', 'nl', 'high'),
  t('de hoer spelen', 'sexual', 'nl', 'high'),
  t('een beurt geven', 'sexual', 'nl', 'high'),
  t('een nummertje maken', 'sexual', 'nl', 'high'),
  t('een wip maken', 'sexual', 'nl', 'high'),
  t('flamoes', 'nudity', 'nl', 'high'),
  t('hoerenbuurt', 'sexual', 'nl', 'high'),
  t('hoerenloper', 'sexual', 'nl', 'high'),
  t('klaarkomen', 'sexual', 'nl', 'high'),
  t('kontneuken', 'sexual', 'nl', 'high'),
  t('kuttelikkertje', 'sexual', 'nl', 'high'),
  t('kwakkie', 'sexual', 'nl', 'high'),
  t('liefdesgrot', 'nudity', 'nl', 'high'),
  t('naakt', 'nudity', 'nl', 'high'),
  t('neuken', 'sexual', 'nl', 'high'),
  t('neukstier', 'sexual', 'nl', 'high'),
  t('op z\'n hondjes', 'sexual', 'nl', 'high'),
  t('pijpbekkieg', 'sexual', 'nl', 'high'),
  t('pijpen', 'sexual', 'nl', 'high'),
  t('pik', 'nudity', 'nl', 'high'),
  t('rukken', 'sexual', 'nl', 'high'),
  t('slik mijn zaad', 'sexual', 'nl', 'high'),
  t('standje-69', 'sexual', 'nl', 'high'),
  t('stoephoer', 'sexual', 'nl', 'high'),
  t('temeier', 'sexual', 'nl', 'high'),
  t('triootjeg', 'sexual', 'nl', 'high'),
  t('trottoir prostituée', 'sexual', 'nl', 'high'),
  t('trottoirteef', 'sexual', 'nl', 'high'),
  t('vingeren', 'sexual', 'nl', 'high'),
  t('vleesroos', 'nudity', 'nl', 'high'),
  t('wippen', 'sexual', 'nl', 'high'),

  // ── pl (11 terms)
  t('burdelmama', 'sexual', 'pl', 'high'),
  t('cyc', 'nudity', 'pl', 'high'),
  t('fiut', 'nudity', 'pl', 'high'),
  t('kutas', 'nudity', 'pl', 'high'),
  t('lizać pałę', 'sexual', 'pl', 'high'),
  t('obciągać chuja', 'sexual', 'pl', 'high'),
  t('obciągać fiuta', 'sexual', 'pl', 'high'),
  t('obciągać loda', 'sexual', 'pl', 'high'),
  t('robic loda', 'sexual', 'pl', 'high'),
  t('robić loda', 'sexual', 'pl', 'high'),
  t('ruchać', 'sexual', 'pl', 'high'),

  // ── pt (21 terms)
  t('balalao', 'nudity', 'pt', 'high'),
  t('boceta', 'nudity', 'pt', 'high'),
  t('braulio de borracha', 'sexual', 'pt', 'high'),
  t('chochota', 'nudity', 'pt', 'high'),
  t('coito', 'sexual', 'pt', 'high'),
  t('cona', 'nudity', 'pt', 'high'),
  t('dar o rabo', 'sexual', 'pt', 'high'),
  t('esporra', 'sexual', 'pt', 'high'),
  t('gozar', 'sexual', 'pt', 'high'),
  t('grelho', 'nudity', 'pt', 'high'),
  t('homoerótico', 'sexual', 'pt', 'high'),
  t('meretriz', 'sexual', 'pt', 'high'),
  t('piroca', 'nudity', 'pt', 'high'),
  t('pirocudo', 'nudity', 'pt', 'high'),
  t('pênis', 'nudity', 'pt', 'high'),
  t('queca', 'sexual', 'pt', 'high'),
  t('transar', 'sexual', 'pt', 'high'),
  t('vibrador', 'sexual', 'pt', 'high'),
  t('xana', 'nudity', 'pt', 'high'),
  t('xochota', 'nudity', 'pt', 'high'),
  t('ânus', 'nudity', 'pt', 'high'),

  // ── ru (14 terms)
  t('trakhat\'sya', 'sexual', 'ru', 'high'),
  t('встать раком', 'sexual', 'ru', 'high'),
  t('выебать', 'sexual', 'ru', 'high'),
  t('голый', 'nudity', 'ru', 'high'),
  t('дрочить', 'sexual', 'ru', 'high'),
  t('играть на кожаной флейте', 'sexual', 'ru', 'high'),
  t('лысого в кулаке гонять', 'sexual', 'ru', 'high'),
  t('малофья', 'sexual', 'ru', 'high'),
  t('манда', 'nudity', 'ru', 'high'),
  t('обнаженный', 'nudity', 'ru', 'high'),
  t('половое сношение', 'sexual', 'ru', 'high'),
  t('секс', 'sexual', 'ru', 'high'),
  t('сиськи', 'nudity', 'ru', 'high'),
  t('траxать', 'sexual', 'ru', 'high'),

  // ── th (11 terms)
  t('กระดอ', 'nudity', 'th', 'high'),
  t('กระหรี่', 'sexual', 'th', 'high'),
  t('กระเด้า', 'sexual', 'th', 'high'),
  t('จิ๋ม', 'nudity', 'th', 'high'),
  t('จู๋', 'nudity', 'th', 'high'),
  t('น้ําแตก', 'sexual', 'th', 'high'),
  t('รูตูด', 'nudity', 'th', 'high'),
  t('หี', 'nudity', 'th', 'high'),
  t('หํา', 'nudity', 'th', 'high'),
  t('อมนกเขา', 'sexual', 'th', 'high'),
  t('เย็ด', 'sexual', 'th', 'high'),

  // ── tr (65 terms)
  t('amcık', 'nudity', 'tr', 'high'),
  t('amcıklar', 'nudity', 'tr', 'high'),
  t('amcıklara', 'nudity', 'tr', 'high'),
  t('amcıklarda', 'nudity', 'tr', 'high'),
  t('amcıklardan', 'nudity', 'tr', 'high'),
  t('amcıkları', 'nudity', 'tr', 'high'),
  t('amcıkların', 'nudity', 'tr', 'high'),
  t('amcıkta', 'nudity', 'tr', 'high'),
  t('amcıktan', 'nudity', 'tr', 'high'),
  t('amcığa', 'nudity', 'tr', 'high'),
  t('amcığı', 'nudity', 'tr', 'high'),
  t('amcığın', 'nudity', 'tr', 'high'),
  t('amlar', 'nudity', 'tr', 'high'),
  t('amı', 'nudity', 'tr', 'high'),
  t('saksocu', 'sexual', 'tr', 'high'),
  t('saksocuda', 'sexual', 'tr', 'high'),
  t('saksocudan', 'sexual', 'tr', 'high'),
  t('saksocular', 'sexual', 'tr', 'high'),
  t('saksoculara', 'sexual', 'tr', 'high'),
  t('saksocularda', 'sexual', 'tr', 'high'),
  t('saksoculardan', 'sexual', 'tr', 'high'),
  t('saksocuları', 'sexual', 'tr', 'high'),
  t('saksocuların', 'sexual', 'tr', 'high'),
  t('saksocunun', 'sexual', 'tr', 'high'),
  t('saksocuya', 'sexual', 'tr', 'high'),
  t('saksocuyu', 'sexual', 'tr', 'high'),
  t('sik', 'nudity', 'tr', 'high'),
  t('siker sikmez', 'sexual', 'tr', 'high'),
  t('siki', 'nudity', 'tr', 'high'),
  t('sikilir sikilmez', 'sexual', 'tr', 'high'),
  t('sikin', 'nudity', 'tr', 'high'),
  t('sikler', 'nudity', 'tr', 'high'),
  t('siklerde', 'nudity', 'tr', 'high'),
  t('siklerden', 'nudity', 'tr', 'high'),
  t('siklere', 'nudity', 'tr', 'high'),
  t('sikleri', 'nudity', 'tr', 'high'),
  t('siklerin', 'nudity', 'tr', 'high'),
  t('sikmek', 'sexual', 'tr', 'high'),
  t('sikmemek', 'sexual', 'tr', 'high'),
  t('sikte', 'nudity', 'tr', 'high'),
  t('sikten', 'nudity', 'tr', 'high'),
  t('taşak', 'nudity', 'tr', 'high'),
  t('taşaklar', 'nudity', 'tr', 'high'),
  t('taşaklara', 'nudity', 'tr', 'high'),
  t('taşaklarda', 'nudity', 'tr', 'high'),
  t('taşaklardan', 'nudity', 'tr', 'high'),
  t('taşakları', 'nudity', 'tr', 'high'),
  t('taşakların', 'nudity', 'tr', 'high'),
  t('taşakta', 'nudity', 'tr', 'high'),
  t('taşaktan', 'nudity', 'tr', 'high'),
  t('taşağa', 'nudity', 'tr', 'high'),
  t('taşağı', 'nudity', 'tr', 'high'),
  t('taşağın', 'nudity', 'tr', 'high'),
  t('yarak', 'nudity', 'tr', 'high'),
  t('yaraklar', 'nudity', 'tr', 'high'),
  t('yaraklara', 'nudity', 'tr', 'high'),
  t('yaraklarda', 'nudity', 'tr', 'high'),
  t('yaraklardan', 'nudity', 'tr', 'high'),
  t('yarakları', 'nudity', 'tr', 'high'),
  t('yarakların', 'nudity', 'tr', 'high'),
  t('yarakta', 'nudity', 'tr', 'high'),
  t('yaraktan', 'nudity', 'tr', 'high'),
  t('yarağa', 'nudity', 'tr', 'high'),
  t('yarağı', 'nudity', 'tr', 'high'),
  t('yarağın', 'nudity', 'tr', 'high'),

  // ── ur (2 terms)
  t('لنڈ', 'nudity', 'ur', 'high'),
  t('لونڈ', 'nudity', 'ur', 'high'),

  // ── zh (86 terms)
  t('三级片', 'pornography', 'zh', 'high'),
  t('乳交', 'sexual', 'zh', 'high'),
  t('乳头', 'nudity', 'zh', 'high'),
  t('乳房', 'nudity', 'zh', 'high'),
  t('乳波臀浪', 'sexual', 'zh', 'high'),
  t('做爱', 'sexual', 'zh', 'high'),
  t('军妓', 'sexual', 'zh', 'high'),
  t('几八', 'nudity', 'zh', 'high'),
  t('几叭', 'nudity', 'zh', 'high'),
  t('几巴', 'nudity', 'zh', 'high'),
  t('几芭', 'nudity', 'zh', 'high'),
  t('包皮', 'nudity', 'zh', 'high'),
  t('卖b', 'sexual', 'zh', 'high'),
  t('卖比', 'sexual', 'zh', 'high'),
  t('卖淫', 'sexual', 'zh', 'high'),
  t('双峰微颤', 'sexual', 'zh', 'high'),
  t('口交', 'sexual', 'zh', 'high'),
  t('叫床', 'sexual', 'zh', 'high'),
  t('后庭', 'nudity', 'zh', 'high'),
  t('吹箫', 'sexual', 'zh', 'high'),
  t('外阴', 'nudity', 'zh', 'high'),
  t('大卵子', 'nudity', 'zh', 'high'),
  t('大卵泡', 'nudity', 'zh', 'high'),
  t('大鸡巴', 'nudity', 'zh', 'high'),
  t('奶子', 'nudity', 'zh', 'high'),
  t('妓女', 'sexual', 'zh', 'high'),
  t('妓院', 'sexual', 'zh', 'high'),
  t('嫖娼', 'sexual', 'zh', 'high'),
  t('嫖客', 'sexual', 'zh', 'high'),
  t('密洞', 'nudity', 'zh', 'high'),
  t('小乳头', 'nudity', 'zh', 'high'),
  t('小卵子', 'nudity', 'zh', 'high'),
  t('小卵泡', 'nudity', 'zh', 'high'),
  t('小肉粒', 'nudity', 'zh', 'high'),
  t('小鸡巴', 'nudity', 'zh', 'high'),
  t('小鸡鸡', 'nudity', 'zh', 'high'),
  t('屁眼', 'nudity', 'zh', 'high'),
  t('屁股眼', 'nudity', 'zh', 'high'),
  t('屄', 'nudity', 'zh', 'high'),
  t('强奸', 'sexual', 'zh', 'high'),
  t('强奸你', 'sexual', 'zh', 'high'),
  t('性器', 'nudity', 'zh', 'high'),
  t('性爱', 'sexual', 'zh', 'high'),
  t('情色', 'pornography', 'zh', 'high'),
  t('懒8', 'nudity', 'zh', 'high'),
  t('懒八', 'nudity', 'zh', 'high'),
  t('懒叫', 'nudity', 'zh', 'high'),
  t('懒教', 'nudity', 'zh', 'high'),
  t('扒光', 'nudity', 'zh', 'high'),
  t('打炮', 'sexual', 'zh', 'high'),
  t('打飞机', 'sexual', 'zh', 'high'),
  t('抽插', 'sexual', 'zh', 'high'),
  t('招妓', 'sexual', 'zh', 'high'),
  t('机八', 'nudity', 'zh', 'high'),
  t('机巴', 'nudity', 'zh', 'high'),
  t('浪叫', 'sexual', 'zh', 'high'),
  t('淫水', 'sexual', 'zh', 'high'),
  t('淫秽', 'pornography', 'zh', 'high'),
  t('淫荡', 'sexual', 'zh', 'high'),
  t('湿透的内裤', 'sexual', 'zh', 'high'),
  t('肉壁', 'nudity', 'zh', 'high'),
  t('肉棍子', 'nudity', 'zh', 'high'),
  t('肉棒', 'nudity', 'zh', 'high'),
  t('肉缝', 'nudity', 'zh', 'high'),
  t('肛交', 'sexual', 'zh', 'high'),
  t('色情', 'pornography', 'zh', 'high'),
  t('轮奸', 'sexual', 'zh', 'high'),
  t('阳具', 'nudity', 'zh', 'high'),
  t('阴唇', 'nudity', 'zh', 'high'),
  t('阴户', 'nudity', 'zh', 'high'),
  t('阴核', 'nudity', 'zh', 'high'),
  t('阴毛', 'nudity', 'zh', 'high'),
  t('阴茎', 'nudity', 'zh', 'high'),
  t('阴道', 'nudity', 'zh', 'high'),
  t('阴部', 'nudity', 'zh', 'high'),
  t('陰莖', 'nudity', 'zh', 'high'),
  t('雞巴', 'nudity', 'zh', 'high'),
  t('鸡8', 'nudity', 'zh', 'high'),
  t('鸡八', 'nudity', 'zh', 'high'),
  t('鸡叭', 'nudity', 'zh', 'high'),
  t('鸡吧', 'nudity', 'zh', 'high'),
  t('鸡奸', 'sexual', 'zh', 'high'),
  t('鸡巴', 'nudity', 'zh', 'high'),
  t('鸡芭', 'nudity', 'zh', 'high'),
  t('鸡鸡', 'nudity', 'zh', 'high'),
  t('龟头', 'nudity', 'zh', 'high'),
];

/** 1201 curated terms + 22 minors additions (Hasan pruning pass 2026-08-26: −41 collision terms). */
export const GENERATION_BLOCKLIST: ModerationTerm[] = [
  ...MINORS_ADDITIONS,
  ...CURATED_TERMS,
];
