import type { AudioModelDefinition } from './types';

/**
 * Base URL for model downloads. Used when downloadPath is a relative path.
 * When downloadPath starts with "http", it's used as-is (direct GitHub URLs).
 * Update this when hosting models on your own server and switch to relative paths.
 */
export const MODELS_BASE_URL = 'https://learnwithhasan.com/api/vidtsx/models/audio';

const GH_ASR = 'https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models';
const GH_TTS = 'https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models';

/**
 * Hardcoded catalog of available audio models.
 * New models are added via app updates.
 */
export const AUDIO_MODEL_CATALOG: AudioModelDefinition[] = [
  // ═══════════════════════════════════════════════════════════════════
  // STT: Offline — Whisper variants
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'sherpa-stt-whisper-tiny',
    name: 'Whisper Tiny',
    type: 'stt',
    sttMode: 'offline',
    language: 'multilingual',
    sizeBytes: 78_000_000,
    sizeLabel: '78 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-tiny.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-tiny',
    files: ['tiny-encoder.int8.onnx', 'tiny-decoder.int8.onnx', 'tiny-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'tiny-encoder.int8.onnx',
      decoder: 'tiny-decoder.int8.onnx',
      tokens: 'tiny-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-whisper-tiny-en',
    name: 'Whisper Tiny (EN only)',
    type: 'stt',
    sttMode: 'offline',
    language: 'en',
    sizeBytes: 60_000_000,
    sizeLabel: '60 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-tiny.en.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-tiny.en',
    files: ['tiny.en-encoder.int8.onnx', 'tiny.en-decoder.int8.onnx', 'tiny.en-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'tiny.en-encoder.int8.onnx',
      decoder: 'tiny.en-decoder.int8.onnx',
      tokens: 'tiny.en-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-whisper-base',
    name: 'Whisper Base',
    type: 'stt',
    sttMode: 'offline',
    language: 'multilingual',
    sizeBytes: 148_000_000,
    sizeLabel: '148 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-base.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-base',
    files: ['base-encoder.int8.onnx', 'base-decoder.int8.onnx', 'base-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'base-encoder.int8.onnx',
      decoder: 'base-decoder.int8.onnx',
      tokens: 'base-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-whisper-base-en',
    name: 'Whisper Base (EN only)',
    type: 'stt',
    sttMode: 'offline',
    language: 'en',
    sizeBytes: 120_000_000,
    sizeLabel: '120 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-base.en.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-base.en',
    files: ['base.en-encoder.int8.onnx', 'base.en-decoder.int8.onnx', 'base.en-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'base.en-encoder.int8.onnx',
      decoder: 'base.en-decoder.int8.onnx',
      tokens: 'base.en-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-whisper-small',
    name: 'Whisper Small',
    type: 'stt',
    sttMode: 'offline',
    language: 'multilingual',
    sizeBytes: 488_000_000,
    sizeLabel: '488 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-small.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-small',
    files: ['small-encoder.int8.onnx', 'small-decoder.int8.onnx', 'small-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'small-encoder.int8.onnx',
      decoder: 'small-decoder.int8.onnx',
      tokens: 'small-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-whisper-small-en',
    name: 'Whisper Small (EN only)',
    type: 'stt',
    sttMode: 'offline',
    language: 'en',
    sizeBytes: 400_000_000,
    sizeLabel: '400 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-small.en.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-small.en',
    files: ['small.en-encoder.int8.onnx', 'small.en-decoder.int8.onnx', 'small.en-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'small.en-encoder.int8.onnx',
      decoder: 'small.en-decoder.int8.onnx',
      tokens: 'small.en-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-whisper-medium',
    name: 'Whisper Medium',
    type: 'stt',
    sttMode: 'offline',
    language: 'multilingual',
    sizeBytes: 1_530_000_000,
    sizeLabel: '1.5 GB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-medium.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-medium',
    files: ['medium-encoder.int8.onnx', 'medium-decoder.int8.onnx', 'medium-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'medium-encoder.int8.onnx',
      decoder: 'medium-decoder.int8.onnx',
      tokens: 'medium-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-whisper-medium-en',
    name: 'Whisper Medium (EN only)',
    type: 'stt',
    sttMode: 'offline',
    language: 'en',
    sizeBytes: 1_200_000_000,
    sizeLabel: '1.2 GB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-medium.en.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-medium.en',
    files: ['medium.en-encoder.int8.onnx', 'medium.en-decoder.int8.onnx', 'medium.en-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'medium.en-encoder.int8.onnx',
      decoder: 'medium.en-decoder.int8.onnx',
      tokens: 'medium.en-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-whisper-large-v3',
    name: 'Whisper Large V3',
    type: 'stt',
    sttMode: 'offline',
    language: 'multilingual',
    sizeBytes: 3_300_000_000,
    sizeLabel: '3.3 GB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-large-v3.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-large-v3',
    files: ['large-v3-encoder.int8.onnx', 'large-v3-decoder.int8.onnx', 'large-v3-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'large-v3-encoder.int8.onnx',
      decoder: 'large-v3-decoder.int8.onnx',
      tokens: 'large-v3-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-distil-whisper-small-en',
    name: 'Distil Whisper Small (EN)',
    type: 'stt',
    sttMode: 'offline',
    language: 'en',
    sizeBytes: 350_000_000,
    sizeLabel: '350 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-distil-small.en.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-distil-small.en',
    files: ['distil-small.en-encoder.int8.onnx', 'distil-small.en-decoder.int8.onnx', 'distil-small.en-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'distil-small.en-encoder.int8.onnx',
      decoder: 'distil-small.en-decoder.int8.onnx',
      tokens: 'distil-small.en-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-distil-whisper-medium-en',
    name: 'Distil Whisper Medium (EN)',
    type: 'stt',
    sttMode: 'offline',
    language: 'en',
    sizeBytes: 1_000_000_000,
    sizeLabel: '1 GB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-distil-medium.en.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-distil-medium.en',
    files: ['distil-medium.en-encoder.int8.onnx', 'distil-medium.en-decoder.int8.onnx', 'distil-medium.en-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'distil-medium.en-encoder.int8.onnx',
      decoder: 'distil-medium.en-decoder.int8.onnx',
      tokens: 'distil-medium.en-tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-distil-whisper-large-v3',
    name: 'Distil Whisper Large V3',
    type: 'stt',
    sttMode: 'offline',
    language: 'multilingual',
    sizeBytes: 2_000_000_000,
    sizeLabel: '2 GB',
    downloadPath: `${GH_ASR}/sherpa-onnx-whisper-distil-large-v3.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-whisper-distil-large-v3',
    files: ['distil-large-v3-encoder.int8.onnx', 'distil-large-v3-decoder.int8.onnx', 'distil-large-v3-tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'whisper',
      sampleRate: 16000,
      encoder: 'distil-large-v3-encoder.int8.onnx',
      decoder: 'distil-large-v3-decoder.int8.onnx',
      tokens: 'distil-large-v3-tokens.txt',
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // STT: Offline — SenseVoice (Alibaba, multilingual Asian)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'sherpa-stt-sensevoice-zh-en-ja-ko',
    name: 'SenseVoice (ZH/EN/JA/KO)',
    type: 'stt',
    sttMode: 'offline',
    language: 'zh,en,ja,ko',
    sizeBytes: 230_000_000,
    sizeLabel: '230 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17',
    files: ['model.int8.onnx', 'tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'paraformer',
      sampleRate: 16000,
      encoder: 'model.int8.onnx',
      decoder: 'model.int8.onnx',
      tokens: 'tokens.txt',
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // STT: Online — Streaming models (live microphone)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'sherpa-stt-zipformer-streaming-en',
    name: 'Zipformer Streaming (EN)',
    type: 'stt',
    sttMode: 'online',
    language: 'en',
    sizeBytes: 68_000_000,
    sizeLabel: '68 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-streaming-zipformer-en-2023-06-26.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-streaming-zipformer-en-2023-06-26',
    files: ['encoder-epoch-99-avg-1.int8.onnx', 'decoder-epoch-99-avg-1.onnx', 'joiner-epoch-99-avg-1.int8.onnx', 'tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'transducer',
      sampleRate: 16000,
      encoder: 'encoder-epoch-99-avg-1.int8.onnx',
      decoder: 'decoder-epoch-99-avg-1.onnx',
      joiner: 'joiner-epoch-99-avg-1.int8.onnx',
      tokens: 'tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-zipformer-streaming-zh-en',
    name: 'Zipformer Streaming (ZH+EN)',
    type: 'stt',
    sttMode: 'online',
    language: 'zh,en',
    sizeBytes: 174_000_000,
    sizeLabel: '174 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-streaming-zipformer-bilingual-zh-en-2023-02-20',
    files: ['encoder-epoch-99-avg-1.int8.onnx', 'decoder-epoch-99-avg-1.onnx', 'joiner-epoch-99-avg-1.int8.onnx', 'tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'transducer',
      sampleRate: 16000,
      encoder: 'encoder-epoch-99-avg-1.int8.onnx',
      decoder: 'decoder-epoch-99-avg-1.onnx',
      joiner: 'joiner-epoch-99-avg-1.int8.onnx',
      tokens: 'tokens.txt',
    },
  },

  {
    id: 'sherpa-stt-paraformer-streaming-zh-en',
    name: 'Paraformer Streaming (ZH+EN+Cantonese)',
    type: 'stt',
    sttMode: 'online',
    language: 'zh,en,yue',
    sizeBytes: 280_000_000,
    sizeLabel: '280 MB',
    downloadPath: `${GH_ASR}/sherpa-onnx-streaming-paraformer-trilingual-zh-cantonese-en.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'sherpa-onnx-streaming-paraformer-trilingual-zh-cantonese-en',
    files: ['encoder.int8.onnx', 'decoder.int8.onnx', 'tokens.txt'],
    sherpaConfig: {
      type: 'stt',
      modelType: 'paraformer',
      sampleRate: 16000,
      encoder: 'encoder.int8.onnx',
      decoder: 'decoder.int8.onnx',
      tokens: 'tokens.txt',
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // TTS — VITS models
  // ═══════════���═══════════════════════════════════════════════════════

  {
    id: 'sherpa-tts-vits-ljs-en',
    name: 'VITS LJSpeech (EN)',
    type: 'tts',
    language: 'en',
    sizeBytes: 75_000_000,
    sizeLabel: '75 MB',
    downloadPath: `${GH_TTS}/vits-ljs.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'vits-ljs',
    files: ['vits-ljs.onnx', 'tokens.txt', 'lexicon.txt'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'vits',
      sampleRate: 22050,
      model: 'vits-ljs.onnx',
      tokens: 'tokens.txt',
      lexicon: 'lexicon.txt',
      numSpeakers: 1,
      defaultSpeakerId: 0,
    },
  },

  {
    id: 'sherpa-tts-vits-vctk-en',
    name: 'VITS VCTK Multi-Speaker (EN)',
    type: 'tts',
    language: 'en',
    sizeBytes: 116_000_000,
    sizeLabel: '116 MB',
    downloadPath: `${GH_TTS}/vits-vctk.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'vits-vctk',
    files: ['vits-vctk.onnx', 'tokens.txt', 'lexicon.txt'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'vits',
      sampleRate: 22050,
      model: 'vits-vctk.onnx',
      tokens: 'tokens.txt',
      lexicon: 'lexicon.txt',
      numSpeakers: 109,
      defaultSpeakerId: 0,
    },
  },

  {
    id: 'sherpa-tts-vits-zh-aishell3',
    name: 'VITS AISHELL3 (ZH)',
    type: 'tts',
    language: 'zh',
    sizeBytes: 116_000_000,
    sizeLabel: '116 MB',
    downloadPath: `${GH_TTS}/vits-zh-aishell3.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'vits-zh-aishell3',
    files: ['vits-aishell3.onnx', 'tokens.txt', 'lexicon.txt'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'vits',
      sampleRate: 22050,
      model: 'vits-aishell3.onnx',
      tokens: 'tokens.txt',
      lexicon: 'lexicon.txt',
      numSpeakers: 174,
      defaultSpeakerId: 0,
    },
  },

  {
    id: 'sherpa-tts-vits-melo-zh-en',
    name: 'MeloTTS (ZH+EN)',
    type: 'tts',
    language: 'zh,en',
    sizeBytes: 90_000_000,
    sizeLabel: '90 MB',
    downloadPath: `${GH_TTS}/vits-melo-tts-zh_en.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'vits-melo-tts-zh_en',
    files: ['model.onnx', 'tokens.txt', 'lexicon.txt'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'vits',
      sampleRate: 22050,
      model: 'model.onnx',
      tokens: 'tokens.txt',
      lexicon: 'lexicon.txt',
      numSpeakers: 1,
      defaultSpeakerId: 0,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // TTS — Piper models (espeak-ng based)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'sherpa-tts-piper-en-glados',
    name: 'Piper GLaDOS (EN)',
    type: 'tts',
    language: 'en',
    sizeBytes: 61_000_000,
    sizeLabel: '61 MB',
    downloadPath: `${GH_TTS}/vits-piper-en_US-glados.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'vits-piper-en_US-glados',
    files: ['en_US-glados.onnx', 'tokens.txt', 'espeak-ng-data'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'piper',
      sampleRate: 22050,
      model: 'en_US-glados.onnx',
      tokens: 'tokens.txt',
      dataDir: 'espeak-ng-data',
      numSpeakers: 1,
      defaultSpeakerId: 0,
    },
  },

  {
    id: 'sherpa-tts-piper-en-amy-medium',
    name: 'Piper Amy (EN)',
    type: 'tts',
    language: 'en',
    sizeBytes: 50_000_000,
    sizeLabel: '50 MB',
    downloadPath: `${GH_TTS}/vits-piper-en_US-amy-medium.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'vits-piper-en_US-amy-medium',
    files: ['en_US-amy-medium.onnx', 'tokens.txt', 'espeak-ng-data'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'piper',
      sampleRate: 22050,
      model: 'en_US-amy-medium.onnx',
      tokens: 'tokens.txt',
      dataDir: 'espeak-ng-data',
      numSpeakers: 1,
      defaultSpeakerId: 0,
    },
  },

  {
    id: 'sherpa-tts-piper-en-lessac-medium',
    name: 'Piper Lessac (EN)',
    type: 'tts',
    language: 'en',
    sizeBytes: 50_000_000,
    sizeLabel: '50 MB',
    downloadPath: `${GH_TTS}/vits-piper-en_US-lessac-medium.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'vits-piper-en_US-lessac-medium',
    files: ['en_US-lessac-medium.onnx', 'tokens.txt', 'espeak-ng-data'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'piper',
      sampleRate: 22050,
      model: 'en_US-lessac-medium.onnx',
      tokens: 'tokens.txt',
      dataDir: 'espeak-ng-data',
      numSpeakers: 1,
      defaultSpeakerId: 0,
    },
  },

  {
    id: 'sherpa-tts-piper-en-libritts-medium',
    name: 'Piper LibriTTS 904-voice (EN)',
    type: 'tts',
    language: 'en',
    sizeBytes: 75_000_000,
    sizeLabel: '75 MB',
    downloadPath: `${GH_TTS}/vits-piper-en_US-libritts_r-medium.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'vits-piper-en_US-libritts_r-medium',
    files: ['en_US-libritts_r-medium.onnx', 'tokens.txt', 'espeak-ng-data'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'piper',
      sampleRate: 22050,
      model: 'en_US-libritts_r-medium.onnx',
      tokens: 'tokens.txt',
      dataDir: 'espeak-ng-data',
      numSpeakers: 904,
      defaultSpeakerId: 0,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // TTS — Kokoro (high quality, multilingual)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'sherpa-tts-kokoro-en-v0-19',
    name: 'Kokoro v0.19 (EN)',
    type: 'tts',
    language: 'en',
    sizeBytes: 350_000_000,
    sizeLabel: '350 MB',
    downloadPath: `${GH_TTS}/kokoro-en-v0_19.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'kokoro-en-v0_19',
    files: ['model.onnx', 'voices.bin', 'tokens.txt', 'espeak-ng-data'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'vits',
      sampleRate: 24000,
      model: 'model.onnx',
      tokens: 'tokens.txt',
      dataDir: 'espeak-ng-data',
      numSpeakers: 11,
      defaultSpeakerId: 0,
    },
  },

  {
    id: 'sherpa-tts-kokoro-multi-v1-0',
    name: 'Kokoro Multi-Lang v1.0 (ZH+EN)',
    type: 'tts',
    language: 'zh,en',
    sizeBytes: 400_000_000,
    sizeLabel: '400 MB',
    downloadPath: `${GH_TTS}/kokoro-multi-lang-v1_0.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'kokoro-multi-lang-v1_0',
    files: ['model.onnx', 'voices.bin', 'tokens.txt', 'espeak-ng-data'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'vits',
      sampleRate: 24000,
      model: 'model.onnx',
      tokens: 'tokens.txt',
      dataDir: 'espeak-ng-data',
      numSpeakers: 53,
      defaultSpeakerId: 0,
    },
  },

  {
    id: 'sherpa-tts-kokoro-multi-v1-1',
    name: 'Kokoro Multi-Lang v1.1 (ZH+EN)',
    type: 'tts',
    language: 'zh,en',
    sizeBytes: 450_000_000,
    sizeLabel: '450 MB',
    downloadPath: `${GH_TTS}/kokoro-multi-lang-v1_1.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'kokoro-multi-lang-v1_1',
    files: ['model.onnx', 'voices.bin', 'tokens.txt', 'espeak-ng-data'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'vits',
      sampleRate: 24000,
      model: 'model.onnx',
      tokens: 'tokens.txt',
      dataDir: 'espeak-ng-data',
      numSpeakers: 103,
      defaultSpeakerId: 0,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // TTS — KittenTTS (ultra-lightweight)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'sherpa-tts-kitten-nano-en',
    name: 'KittenTTS Nano (EN)',
    type: 'tts',
    language: 'en',
    sizeBytes: 25_000_000,
    sizeLabel: '25 MB',
    downloadPath: `${GH_TTS}/kitten-nano-en-v0_1-fp16.tar.bz2`,
    archiveFormat: 'tar.bz2',
    extractedDirName: 'kitten-nano-en-v0_1-fp16',
    files: ['model.fp16.onnx', 'voices.bin', 'tokens.txt', 'espeak-ng-data'],
    sherpaConfig: {
      type: 'tts',
      modelType: 'vits',
      sampleRate: 22050,
      model: 'model.fp16.onnx',
      tokens: 'tokens.txt',
      dataDir: 'espeak-ng-data',
      numSpeakers: 8,
      defaultSpeakerId: 0,
    },
  },
];
