import { logEngine } from '../../logging/log-engine';
import * as esbuild from 'esbuild';
import fs from 'fs/promises';
import path from 'path';
import { createHash } from 'crypto';

const log = logEngine.createLogger('Transpiler');
import { CDN_CONFIG, KNOWN_PACKAGE_VERSIONS, VIRTUAL_PACKAGES } from '@shared/constants';
import { rewriteFontUrls } from './font-proxy';
import {
  DEFAULT_CONFIG,
  parseCompositionConfig,
  type CompositionConfig,
} from './composition-config-parser';

export type { CompositionConfig };

export interface TranspileResult {
  success: true;
  code: string;
  hash: string;
  config: CompositionConfig;
  componentName: string;
}

export interface TranspileError {
  success: false;
  error: string;
  location?: {
    line: number;
    column: number;
    file: string;
  };
}

export type TranspileOutput = TranspileResult | TranspileError;

/**
 * Find the component export name from the file content
 */
function findComponentExport(content: string): string {
  // Pattern 1: export default function Name
  const defaultFuncMatch = content.match(/export\s+default\s+function\s+(\w+)/);
  if (defaultFuncMatch) {
    return defaultFuncMatch[1];
  }

  // Pattern 2: export default Name (where Name is defined elsewhere)
  const defaultNameMatch = content.match(/export\s+default\s+(\w+)\s*;/);
  if (defaultNameMatch) {
    return defaultNameMatch[1];
  }

  // Pattern 3: export function Name (named export)
  const namedFuncMatch = content.match(/export\s+function\s+(\w+)\s*\(/);
  if (namedFuncMatch) {
    return namedFuncMatch[1];
  }

  // Pattern 4: const Name = () => ... then export default Name
  const componentMatch = content.match(/(?:const|let)\s+(\w+)(?:\s*:\s*React\.FC)?(?:<[^>]*>)?\s*=/);
  if (componentMatch) {
    const exportDefaultPattern = new RegExp(`export\\s+default\\s+${componentMatch[1]}\\b`);
    if (exportDefaultPattern.test(content)) {
      return componentMatch[1];
    }
  }

  return 'UserComponent';
}

/**
 * Check if the file has a default export
 */
function hasDefaultExport(content: string): boolean {
  return /export\s+default\s+/.test(content);
}

// Packages that use React and need aliasing to share the same React instance
const REACT_DEPENDENT_PACKAGES = new Set([
  '@react-three/fiber',
  '@react-three/drei',
  '@react-three/postprocessing',
  'framer-motion',
  'motion',
  '@lottiefiles/react-lottie-player',
  'react-simple-maps',
]);

// @remotion/* packages that contain React components/hooks and need
// both React AND Remotion aliasing to share the same instances
const REMOTION_COMPONENT_PACKAGES = new Set([
  '@remotion/three',
  '@remotion/transitions',
  '@remotion/google-fonts',
  '@remotion/media-utils',
]);

/**
 * Split a bare import specifier into its root package name and subpath.
 * Handles scoped packages (@scope/pkg/sub) and unscoped (pkg/sub).
 *
 * Examples:
 *   '@remotion/transitions/fade' → { root: '@remotion/transitions', subpath: '/fade' }
 *   '@remotion/google-fonts/Lobster' → { root: '@remotion/google-fonts', subpath: '/Lobster' }
 *   'lodash-es/merge' → { root: 'lodash-es', subpath: '/merge' }
 *   'react' → { root: 'react', subpath: '' }
 */
function splitPackage(spec: string): { root: string; subpath: string } {
  if (spec.startsWith('@')) {
    const parts = spec.split('/');
    if (parts.length <= 2) return { root: spec, subpath: '' };
    return { root: `${parts[0]}/${parts[1]}`, subpath: '/' + parts.slice(2).join('/') };
  }
  const idx = spec.indexOf('/');
  if (idx === -1) return { root: spec, subpath: '' };
  return { root: spec.slice(0, idx), subpath: spec.slice(idx) };
}

// Packages pre-bundled locally and served by the module server's /vendor/
// route. Generated by scripts/build-vendor.mjs into resources/vendor/.
// If a package is here, we NEVER hit esm.sh — the bundled file is used.
const LOCAL_VENDOR_PACKAGES: Record<string, string> = {
  'three': 'three.js',
  '@react-three/fiber': 'react-three-fiber.js',
  '@react-three/drei': 'react-three-drei.js',
  '@remotion/three': 'remotion-three.js',
};

// Packages routed to a /virtual/ shim instead of the raw vendor bundle. The
// shim wraps or augments the underlying module — used today for
// @remotion/three to insert a per-scene Suspense boundary that stops drei
// <Text> (and other async R3F children) from blanking the whole canvas.
const VIRTUAL_SHIM_PACKAGES: Record<string, string> = {
  '@remotion/three': 'remotion-three.js',
};

// Packages whose transitive deps should be inlined by esm.sh (?bundle-deps).
// Only used when a package is NOT in LOCAL_VENDOR_PACKAGES (esm.sh fallback).
const BUNDLE_DEPS_PACKAGES = new Set<string>([
  '@react-three/drei',
]);

// Per-package peer-dep version pins for esm.sh fallback. Values MUST match
// KNOWN_PACKAGE_VERSIONS. Unused once a package moves to LOCAL_VENDOR_PACKAGES.
const PEER_DEPS_PINS: Record<string, string[]> = {
  '@react-three/drei': [
    'three@0.162.0',
    '@react-three/fiber@8.15.19',
  ],
};

/**
 * Build a URL for an external package import.
 *  - Packages in LOCAL_VENDOR_PACKAGES → served locally from /vendor/<filename>.
 *  - All others → fall back to esm.sh with aliasing + optional bundle-deps/deps.
 *
 * The esm.sh fallback will be removed in Phase 2 once all packages are vendored.
 */
function buildCdnUrl(packageName: string, baseUrl: string): string {
  // Split subpath imports (e.g. '@remotion/transitions/fade') so we look up
  // versions/aliases/vendors by the root package name but preserve the
  // subpath in the final URL.
  const { root, subpath } = splitPackage(packageName);

  // Virtual shim — overrides the vendor bundle for packages that need
  // wrapping (e.g. @remotion/three's Suspense fix). Only matches the root.
  const shimFile = VIRTUAL_SHIM_PACKAGES[root];
  if (shimFile && !subpath) {
    return `${baseUrl}/virtual/${shimFile}`;
  }

  // Local vendor bundle — the fast path. Only matches the root package;
  // subpath imports always fall through to the esm.sh path.
  const vendorFile = LOCAL_VENDOR_PACKAGES[root];
  if (vendorFile && !subpath) {
    return `${baseUrl}/vendor/${vendorFile}`;
  }
  const version = KNOWN_PACKAGE_VERSIONS[root] ?? 'latest';
  const params: string[] = [];

  // 1. alias — share React/ReactDOM (+ Remotion) instances with the Player.
  const aliasParts: string[] = [];
  if (REMOTION_COMPONENT_PACKAGES.has(root)) {
    aliasParts.push(
      `react:${baseUrl}/virtual/react.js`,
      `react-dom:${baseUrl}/virtual/react-dom.js`,
      `remotion:${baseUrl}/virtual/remotion.js`,
    );
  } else if (REACT_DEPENDENT_PACKAGES.has(root) || root.startsWith('@react-')) {
    aliasParts.push(
      `react:${baseUrl}/virtual/react.js`,
      `react-dom:${baseUrl}/virtual/react-dom.js`,
    );
  }
  if (aliasParts.length > 0) {
    params.push(`alias=${aliasParts.join(',')}`);
  }

  // 2. deps — pin peer versions through the transitive graph.
  const pins = PEER_DEPS_PINS[root];
  if (pins && pins.length > 0) {
    params.push(`deps=${pins.join(',')}`);
  }

  // 3. bundle-deps — inline transitive deps for packages that need it.
  if (BUNDLE_DEPS_PACKAGES.has(root)) {
    params.push('bundle-deps');
  }

  const query = params.length > 0 ? `?${params.join('&')}` : '';
  return `${CDN_CONFIG.BASE_URL}/${root}@${version}${subpath}${query}`;
}

/**
 * Rewrite imports to use virtual module URLs or CDN
 * - react, react-dom, remotion -> virtual modules (shared instances)
 * - other packages -> esm.sh CDN
 */
function rewriteImports(code: string, baseUrl: string): string {
  // Step 1: Rewrite virtual packages to local module server
  // Remotion imports
  code = code.replace(
    /from\s*['"]remotion['"]/g,
    `from '${baseUrl}/virtual/remotion.js'`
  );

  // React imports
  code = code.replace(
    /from\s*['"]react['"]/g,
    `from '${baseUrl}/virtual/react.js'`
  );

  // React DOM imports
  code = code.replace(
    /from\s*['"]react-dom['"]/g,
    `from '${baseUrl}/virtual/react-dom.js'`
  );

  // React JSX runtime (handled later in transpileTsx, but also here for completeness)
  code = code.replace(
    /from\s*['"]react\/jsx-runtime['"]/g,
    `from '${baseUrl}/virtual/react-jsx-runtime.js'`
  );

  code = code.replace(
    /from\s*['"]react\/jsx-dev-runtime['"]/g,
    `from '${baseUrl}/virtual/react-jsx-runtime.js'`
  );

  // Step 1b: Fix default imports of packages that have no default export on esm.sh.
  // `tone` is pure ESM — esm.sh serves it with `export *` and no default export.
  // The AI sometimes generates `import Tone from 'tone'` which fails at runtime.
  // Rewrite to `import * as Tone from 'tone'` (namespace import) so it works.
  code = code.replace(
    /import\s+(\w+)\s+from\s*(['"])tone\2/g,
    `import * as $1 from $2tone$2`
  );

  // Step 2: Rewrite remaining bare imports to CDN
  // Match: from 'package-name' or from '@scope/package-name'
  // Skip: relative paths (./foo, ../bar, /absolute) and already-rewritten URLs
  const bareImportRegex = /from\s*['"]([^'"./][^'"]*)['"]/g;

  code = code.replace(bareImportRegex, (match, packageName: string) => {
    // Skip packages already handled by virtual modules
    if (VIRTUAL_PACKAGES.has(packageName)) {
      return match;
    }

    // Skip if already rewritten to a URL
    if (packageName.startsWith('http://') || packageName.startsWith('https://')) {
      return match;
    }

    // Rewrite to CDN URL
    const cdnUrl = buildCdnUrl(packageName, baseUrl);
    log.debug(`Rewriting external import: ${packageName} -> ${cdnUrl}`);
    return `from '${cdnUrl}'`;
  });

  // Step 3: Route Google Fonts URLs in string literals (e.g. drei <Text font="...">)
  // through the local proxy so the webview's CSP can't block them and offline
  // loads hit the on-disk cache instead of the network.
  code = rewriteFontUrls(code, baseUrl);

  return code;
}

/**
 * Transpile TSX source (already in memory) to ESM JavaScript.
 * sourceName is used only for error reporting / sourcemaps.
 */
export async function transpileTsxSource(
  content: string,
  sourceName: string,
  moduleServerBaseUrl: string
): Promise<TranspileOutput> {
  try {
    // Generate hash for caching
    const hash = createHash('md5').update(content).digest('hex').slice(0, 12);

    // Parse config and find component
    const config = parseCompositionConfig(content) ?? { ...DEFAULT_CONFIG };
    const componentName = findComponentExport(content);
    const isDefaultExport = hasDefaultExport(content);

    // Transpile with esbuild
    const result = await esbuild.transform(content, {
      loader: 'tsx',
      jsx: 'automatic',
      jsxImportSource: 'react',
      format: 'esm',
      target: 'es2020',
      sourcemap: 'inline',
      sourcefile: sourceName,
    });

    // Rewrite imports to use virtual modules and CDN for external packages
    let transpiledCode = rewriteImports(result.code, moduleServerBaseUrl);

    // Ensure the component is exported as default for lazyComponent
    if (!isDefaultExport) {
      // Add a default export for the component
      transpiledCode += `\nexport default ${componentName};\n`;
    }

    return {
      success: true,
      code: transpiledCode,
      hash,
      config,
      componentName,
    };
  } catch (err) {
    // Handle esbuild errors
    if (err instanceof Error && 'errors' in err) {
      const esbuildErr = err as esbuild.TransformFailure;
      const firstError = esbuildErr.errors[0];

      return {
        success: false,
        error: firstError?.text ?? 'Unknown transpilation error',
        location: firstError?.location
          ? {
              line: firstError.location.line,
              column: firstError.location.column,
              file: sourceName,
            }
          : undefined,
      };
    }

    return {
      success: false,
      error: err instanceof Error ? err.message : 'Unknown error',
    };
  }
}

/**
 * Transpile a TSX file to ESM JavaScript
 */
export async function transpileTsx(
  filePath: string,
  moduleServerBaseUrl: string
): Promise<TranspileOutput> {
  let content: string;
  try {
    content = await fs.readFile(filePath, 'utf-8');
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Unknown error',
    };
  }
  // Pass the full path so error locations keep pointing at the real file.
  return transpileTsxSource(content, filePath, moduleServerBaseUrl);
}

/**
 * Cache for transpiled modules
 */
const transpileCache = new Map<string, TranspileResult>();

/**
 * Transpile with caching
 */
export async function transpileTsxCached(
  filePath: string,
  moduleServerBaseUrl: string
): Promise<TranspileOutput> {
  // Read file to get content hash
  const content = await fs.readFile(filePath, 'utf-8');
  const cacheKey = createHash('md5').update(content).digest('hex');

  // Check cache
  const cached = transpileCache.get(cacheKey);
  if (cached) {
    return cached;
  }

  // Transpile
  const result = await transpileTsx(filePath, moduleServerBaseUrl);

  // Cache successful results
  if (result.success) {
    transpileCache.set(cacheKey, result);
  }

  return result;
}

/**
 * Clear the transpile cache
 */
export function clearTranspileCache(): void {
  transpileCache.clear();
}
