/**
 * AI runtime catalogue — the two downloadable Python + PyTorch stacks the app can
 * install (docs/ai-runtime-implementation-plan.md §3 step 1). One runtime version is
 * live per app version; both variants are built from the same lock by
 * scripts/ai-runtime/build-stack.ps1, which prints these entries. Never edit the
 * numbers by hand: rebuild, verify, upload, paste.
 *
 * No `electron` import — this module is unit-tested in plain Node.
 */
import type { AiRuntimeVariant } from '@shared/ipc/types/ai-runtime';

export type { AiRuntimeVariant };

/** The runtime version this app version pins (YYYY.MM.N). */
export const AI_RUNTIME_VERSION = '2026.09.1';

/** Public base of the R2 bucket (custom domain; bucket vidtsx-cdn, prefix ai-runtime/). */
export const AI_RUNTIME_R2_BASE = 'https://cdn.vidtsx.com/ai-runtime';

/** Download-task metadata.type — the renderer filters DOWNLOAD_PROGRESS on it. */
export const AI_RUNTIME_DOWNLOAD_TYPE = 'ai-runtime';

export const AI_RUNTIME_VARIANTS: readonly AiRuntimeVariant[] = ['cu126', 'cpu'];

export interface AiRuntimeCatalogueEntry {
  version: string;
  variant: AiRuntimeVariant;
  /** Primary URL first, mirrors after (download engine falls through on hard failure). */
  urls: readonly string[];
  /** sha256 of the zip. */
  sha256: string;
  /** Bytes of the zip. */
  bytes: number;
  /** Bytes once extracted (manifest.json excluded), for the disk guard. */
  bytesOnDisk: number;
  files: number;
  /** Folder inside the zip holding python.exe. */
  extractedDir: 'python';
  python: string;
  torch: string;
  /** CUDA runtime line bundled with torch, null for the CPU build. */
  cuda: string | null;
  /** Minimum NVIDIA driver for the bundled CUDA line, null for the CPU build. */
  minDriver: string | null;
  /**
   * Deepest relative path inside the extracted runtime, in characters. The
   * preflight refuses to install when len(root) + this + 1 > 259 on a Windows
   * without LongPathsEnabled (Stage 0 relocation finding).
   */
  maxRelativePathLength: number;
  /** sha256 of requirements.<variant>.lock (LF-normalised) the build was synced from. */
  lockSha256: string;
  licence: string;
}

export const AI_RUNTIME_CATALOGUE: Record<AiRuntimeVariant, AiRuntimeCatalogueEntry> = {
  // Generated by scripts/ai-runtime/build-stack.ps1 cu126 2026.09.1 on 2026-09-04T20:09:55Z
  cu126: {
    version: '2026.09.1',
    variant: 'cu126',
    urls: [`${AI_RUNTIME_R2_BASE}/2026.09.1-cu126.zip`],
    sha256: '8a8fe1f4e776b328df01df2f3459e251f400f6161e0a6c5dad8a259446b46359',
    bytes: 2758592573,
    bytesOnDisk: 4613287893,
    files: 14218,
    extractedDir: 'python',
    python: '3.11.15',
    torch: '2.14.0+cu126',
    cuda: '12.6',
    minDriver: '525.60',
    maxRelativePathLength: 126,
    lockSha256: 'b6249d7011e4d2e5f0fa02e7f49c50088508c94ee9ba8c99a428073050ee0ab4',
    licence: 'PSF-2.0 (CPython), BSD-3-Clause (PyTorch), NVIDIA EULA (CUDA redistributables); per-package notices in licenses/',
  },
  // Generated by scripts/ai-runtime/build-stack.ps1 cpu 2026.09.1 on 2026-09-04T20:20:31Z
  cpu: {
    version: '2026.09.1',
    variant: 'cpu',
    urls: [`${AI_RUNTIME_R2_BASE}/2026.09.1-cpu.zip`],
    sha256: '4268ccfd3062f18474e81de185fa8a20598adf423c52e7a193c223da860895c1',
    bytes: 279969216,
    bytesOnDisk: 899222488,
    files: 14190,
    extractedDir: 'python',
    python: '3.11.15',
    torch: '2.14.0+cpu',
    cuda: null,
    minDriver: null,
    maxRelativePathLength: 126,
    lockSha256: 'b50c2c460e4dce20a294dc3de18e45bfcbd9bc92ad76bcd0ab40518788ce07ce',
    licence: 'PSF-2.0 (CPython), BSD-3-Clause (PyTorch); per-package notices in licenses/',
  },
};

/** Folder name of an installed runtime: `<version>-<variant>`. */
export function aiRuntimeDirName(version: string, variant: AiRuntimeVariant): string {
  return `${version}-${variant}`;
}

/** Download-task id per variant (one task at a time per variant). */
export function aiRuntimeDownloadId(variant: AiRuntimeVariant): string {
  return `ai-runtime-${variant}`;
}

/** "2.6 GB" / "267 MB" for UI labels. */
export function formatRuntimeBytes(bytes: number): string {
  if (bytes >= 1_000_000_000) return `${(bytes / 1_000_000_000).toFixed(1)} GB`;
  return `${Math.round(bytes / 1_000_000)} MB`;
}

const DIR_NAME_RE = /^(\d{4}\.\d{2}\.\d+)-(cu126|cpu)$/;

/** Parse `<version>-<variant>` back into its parts; null for anything else (e.g. `.tmp` staging). */
export function parseAiRuntimeDirName(name: string): { version: string; variant: AiRuntimeVariant } | null {
  const m = DIR_NAME_RE.exec(name);
  if (!m) return null;
  return { version: m[1], variant: m[2] as AiRuntimeVariant };
}
