import { describe, expect, it } from 'vitest';
import { buildGenerate3dPrompt, buildLibraryMeshesSection } from './generate-3d-prompt';

describe('Library meshes section (plan §5 step 7)', () => {
  it('is absent without meshes', () => {
    expect(buildLibraryMeshesSection(undefined)).toBe('');
    expect(buildLibraryMeshesSection([])).toBe('');
    expect(buildGenerate3dPrompt({})).not.toContain('## Library meshes');
  });

  it('lists the meshes with forward slashes, descriptions and the TripoSR remap note', () => {
    const prompt = buildGenerate3dPrompt({
      libraryMeshes: [
        { path: 'C:\\Users\\me\\Assets\\generated\\3d\\chair.glb', description: '3D model of chair.png (TripoSR, 256³)', generated: true },
        { path: 'C:\\Users\\me\\Assets\\imports\\robot.glb' },
      ],
    });
    expect(prompt).toContain('## Library meshes');
    expect(prompt).toContain('`C:/Users/me/Assets/generated/3d/chair.glb` — 3D model of chair.png (TripoSR, 256³) (generated by TripoSR');
    expect(prompt).toContain('`C:/Users/me/Assets/imports/robot.glb`');
    expect(prompt).toContain('useGLTF(staticFile(');
    expect(prompt).toContain("new THREE.Euler(-Math.PI / 2, -Math.PI / 2, 0, 'YXZ')");
    // The section sits before the traps so the recipe is read as an allowed pattern.
    expect(prompt.indexOf('## Library meshes')).toBeLessThan(prompt.indexOf('## Critical traps'));
  });
});
