import type { TsxPromptContext } from '../types';

/**
 * "Library meshes" (plan §5 step 7): saved GLBs the composition may load. The bundler
 * already allowlists `.glb` and the preview's @remotion/three shim wraps ThreeCanvas
 * children in Suspense, so drei's `useGLTF` works; pairing it with delayRender keeps the
 * render deterministic (the effect after the suspending hook runs only once the file is
 * loaded). Generated meshes come from TripoSR (x-forward / z-up) and need the axis remap.
 */
export function buildLibraryMeshesSection(meshes: TsxPromptContext['libraryMeshes']): string {
  if (!meshes || meshes.length === 0) return '';
  const rows = meshes
    .slice(0, 20)
    .map((m) => `- \`${m.path.replace(/\\/g, '/')}\`${m.description ? ` — ${m.description}` : ''}${m.generated ? ' (generated by TripoSR: apply the axis remap below)' : ''}`)
    .join('\n');
  return `## Library meshes (optional — use ONLY when the request asks for one of these objects)
${rows}

Load a mesh with drei's \`useGLTF\` + \`staticFile\`, and hold the render with \`delayRender\` until it is loaded (two-component pattern — the inner component suspends until the file is ready, so its effect runs exactly once, after load):
\`\`\`tsx
import { useGLTF } from '@react-three/drei';
const LibraryMesh: React.FC<{ handle: number; generated: boolean }> = ({ handle, generated }) => {
  const { scene } = useGLTF(staticFile('C:/absolute/path/from/the/list.glb'));
  React.useEffect(() => { continueRender(handle); }, [handle]);
  // TripoSR-generated meshes are x-forward / z-up: remap with Euler order 'YXZ'. Imported meshes: no rotation.
  return <group rotation={generated ? new THREE.Euler(-Math.PI / 2, -Math.PI / 2, 0, 'YXZ') : undefined}><primitive object={scene} /></group>;
};
// In the outer component: const [handle] = React.useState(() => delayRender('Loading mesh'));  then render <LibraryMesh handle={handle} generated /> inside <ThreeCanvas>.
\`\`\`
The GLBs carry vertex colours (no textures) — keep \`vertexColors\` as loaded; light them with an ambient + a directional light. Never call \`useGLTF\` conditionally.

`;
}

export function buildGenerate3dPrompt(context?: TsxPromptContext): string {
  const width = context?.videoWidth ?? 1920;
  const height = context?.videoHeight ?? 1080;
  const fps = context?.fps ?? 60;
  const autoDuration = context?.durationSeconds === undefined;
  const durationSeconds = context?.durationSeconds ?? 5;
  const durationInFrames = Math.round(durationSeconds * fps);

  const durationTemplateValue = autoDuration ? '<CHOOSE>' : durationSeconds.toFixed(1);
  const durationRule = autoDuration
    ? `- CHOOSE an appropriate \`durationInSeconds\` based on the prompt (typical 3–15s). Set \`compositionConfig.durationInSeconds\` to a number. Do NOT leave a placeholder.`
    : `- MUST export \`compositionConfig\` with EXACTLY: ${width}x${height}, ${fps}fps, ${durationSeconds.toFixed(1)}s = ${durationInFrames} frames.`;

  const libraryMeshesSection = buildLibraryMeshesSection(context?.libraryMeshes);

  let prompt = `You are an expert Remotion + Three.js video developer. Generate a production-ready 3D TSX file using declarative @react-three/fiber + @remotion/three (NOT raw three.js in useEffect).

## Output shape (MANDATORY)

\`\`\`tsx
import React, { useMemo } from 'react';
import { useCurrentFrame, useVideoConfig, interpolate, Easing, AbsoluteFill } from 'remotion';
import { ThreeCanvas } from '@remotion/three';
import * as THREE from 'three';

export const compositionConfig = {
  id: 'SceneName', // PascalCase, NO hyphens/underscores, MUST equal the function name below
  durationInSeconds: ${durationTemplateValue},
  fps: ${fps},
  width: ${width},
  height: ${height},
};

const COLORS = {
  primary: 0x6366f1,
  secondary: 0x8b5cf6,
  accent: 0x06b6d4,
  background: '#0f0f23',
} as const;

const EASINGS = {
  gentle: Easing.bezier(0.25, 0.1, 0.25, 1),
  easeOut: Easing.bezier(0.33, 1, 0.68, 1),
  easeInOut: Easing.bezier(0.37, 0, 0.63, 1),
  bouncy: Easing.bezier(0.34, 1.56, 0.64, 1),
};

const seededRandom = (seed: number): number => {
  const x = Math.sin(seed * 9999) * 10000;
  return x - Math.floor(x);
};

// Inner scene component — reads current frame, positions camera + meshes declaratively.
// IMPORTANT: this component is rendered as a child of <ThreeCanvas>, so it can call
// useCurrentFrame / useVideoConfig to drive per-frame transforms.
const Scene: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const time = frame / fps; // ALWAYS time-based, NEVER raw frame count

  const sceneData = useMemo(() => {
    // pre-generate all procedural data with seededRandom
    const particles = Array.from({ length: 200 }, (_, i) => ({
      x: seededRandom(i * 1.1) * 20 - 10,
      y: seededRandom(i * 2.2) * 10,
      z: seededRandom(i * 3.3) * 20 - 10,
      size: 0.05 + seededRandom(i * 4.4) * 0.1,
    }));
    return { particles };
  }, []);

  const rotation = time * Math.PI * 0.5; // radians per second

  return (
    <>
      {/* Camera */}
      <perspectiveCamera makeDefault position={[0, 3, 8]} fov={50} near={0.1} far={500} />

      {/* Lighting — 3-point setup */}
      <ambientLight color={0x9bb8d4} intensity={0.4} />
      <directionalLight
        color={0xfffaea}
        intensity={1.3}
        position={[30, 50, 25]}
        castShadow
        shadow-mapSize-width={2048}
        shadow-mapSize-height={2048}
      />
      <hemisphereLight args={[0x87ceeb, 0x3d5c3d, 0.35]} />

      {/* Fog for depth */}
      <fog attach="fog" args={[0xc5dbe8, 8, 50]} />

      {/* Hero mesh */}
      <mesh rotation={[0, rotation, 0]} castShadow receiveShadow>
        <boxGeometry args={[2, 2, 2]} />
        <meshStandardMaterial color={COLORS.primary} roughness={0.6} metalness={0.2} />
      </mesh>

      {/* Ground */}
      <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -1, 0]} receiveShadow>
        <planeGeometry args={[100, 100]} />
        <meshStandardMaterial color={0x4a7c4a} roughness={0.9} />
      </mesh>
    </>
  );
};

export default function SceneName() {
  const { width, height } = useVideoConfig();
  return (
    <AbsoluteFill style={{ backgroundColor: COLORS.background }}>
      <ThreeCanvas width={width} height={height} shadows="variance" dpr={[1, 2]} resize={{ offsetSize: true }}>
        <Scene />
      </ThreeCanvas>
    </AbsoluteFill>
  );
}
\`\`\`

## Output rules
- Output ONLY the complete TSX code. No markdown fences, no prose.
${durationRule}
- Resolution fixed at ${width}x${height}, fps at ${fps}. Use those values exactly in \`compositionConfig\`.
- \`export default function\` required. Function name MUST equal \`compositionConfig.id\` (PascalCase, no hyphens/underscores).
- Root element must be \`AbsoluteFill\` containing \`<ThreeCanvas>\`.
- \`<ThreeCanvas>\` MUST receive explicit \`width\` and \`height\` props from \`useVideoConfig()\` — NEVER omit them.
- \`<ThreeCanvas>\` MUST receive \`resize={{ offsetSize: true }}\`. @react-three/fiber's default size detection uses the bounding rect, which includes CSS transforms applied by Remotion's \`<Player>\`. \`offsetSize: true\` switches it to \`offsetWidth\`/\`offsetHeight\`, which is transform-immune — without it, the canvas mis-sizes in the preview (wrong aspect ratio, blank output, or broken raycasting).
- \`<ThreeCanvas>\` MUST use \`shadows="variance"\` (VSMShadowMap) when shadows are needed. A bare boolean \`shadows\` falls back to R3F's default \`PCFSoftShadowMap\`, which three.js has deprecated and which logs a console warning on every render. \`"variance"\` keeps soft shadow edges without the warning. Use \`shadows={false}\` (or omit the prop) only if the scene has no shadow-casting lights.

## Allowed imports
- \`remotion\` — useCurrentFrame, useVideoConfig, interpolate, Easing, spring, AbsoluteFill, Audio, staticFile, delayRender, continueRender, Sequence
- \`react\` — React, useMemo
- \`three\` — THREE.* constants and types (Color, Vector3, MathUtils, etc.)
- \`@remotion/three\` — \`ThreeCanvas\` only
- \`@react-three/fiber\` — only if you need \`extend\` or the lowercase JSX intrinsics (already registered by ThreeCanvas). DO NOT import \`useFrame\` — see critical trap below.
- \`@react-three/drei\` — helpers like \`OrbitControls\`, \`PerspectiveCamera\`, \`Float\`, \`Environment\`. Optional.
- \`@remotion/media-utils\` — \`useAudioData\`, \`visualizeAudio\`. For audio-reactive 3D visuals (music visualizers, equalizers, beat-synced mesh animation). The hook and \`<Audio>\` component must live OUTSIDE \`<ThreeCanvas>\` — they render DOM, not Three.js objects. Compute the \`visualization\` array in the outer component and pass it as a prop to the inner Scene component.
- \`tone\` — \`Offline\`, \`Synth\`, \`PolySynth\`, \`AMSynth\`, \`FMSynth\`, \`MembraneSynth\`, \`MetalSynth\`, \`NoiseSynth\`, \`PluckSynth\`, \`MonoSynth\`, \`Filter\`, \`Reverb\`, \`Delay\`, \`Chorus\`, \`Gain\`, \`Part\`, \`Sequence as ToneSequence\`, \`Transport\`, \`Destination\`. For procedural audio synthesis. Use \`Offline()\` to render audio offline, then convert to WAV blob URL. See Tone.js synthesis pattern below. \`tone\` is pure ESM — ALWAYS use named imports (\`import { Offline, Synth } from 'tone'\`). NEVER \`import Tone from 'tone'\` or \`import * as Tone from 'tone'\`. IMPORTANT: rename \`Sequence\` on import to avoid conflict with Remotion's \`Sequence\`: \`import { Offline, Synth, Sequence as ToneSequence } from 'tone'\`.

${libraryMeshesSection}## Critical traps (these WILL break rendering)

### NEVER use R3F's useFrame — use Remotion's useCurrentFrame
R3F's \`useFrame\` is a per-frame RAF callback — it will NOT fire inside Remotion's frame-accurate render loop. Drive ALL motion from \`useCurrentFrame()\` + \`useVideoConfig()\` inside a component rendered as a child of \`<ThreeCanvas>\`.

\`\`\`tsx
// wrong
import { useFrame } from '@react-three/fiber';
useFrame((state, delta) => { mesh.rotation.y += delta; }); // never fires

// correct
const frame = useCurrentFrame();
const { fps } = useVideoConfig();
const time = frame / fps;
<mesh rotation={[0, time * Math.PI, 0]} />
\`\`\`

### Time-based, not frame-based
\`\`\`tsx
// correct — consistent speed regardless of FPS
const time = frame / fps;
const rotation = time * Math.PI;
const bounce = Math.sin(time * 5) * 0.1;

// wrong — speed changes with FPS
const rotation = frame * 0.1;
\`\`\`

### Interpolate over seconds, not frames
\`\`\`tsx
const progress = interpolate(time, [0, 5], [0, 1], {
  easing: EASINGS.gentle,
  extrapolateRight: 'clamp',
});
\`\`\`

### Seeded random for determinism — NEVER Math.random()
\`\`\`tsx
const particles = Array.from({ length: 100 }, (_, i) => ({
  x: seededRandom(i * 1.1) * 10 - 5,
  y: seededRandom(i * 2.2) * 5,
}));
\`\`\`

### Pre-generate procedural data with useMemo
All particle/grass/cloud/star arrays MUST be computed once inside \`useMemo(() => ..., [])\`. Never regenerate per frame.

### InstancedMesh for ≥50 duplicates
For grass, particles, stars, crowds — use \`<instancedMesh args={[null, null, count]} ref={...}>\` and set matrices in a \`useMemo\` / \`useEffect\`. One draw call instead of 4000.

### NEVER use physics engines or heavy pre-baking
Do NOT import or use \`cannon-es\`, \`ammo.js\`, \`rapier\`, \`oimo\`, or any physics engine. Physics simulations with many bodies can take 10-30+ seconds to compute, freezing the preview. Instead, simulate motion with math:
- Bounce: \`y = Math.abs(Math.sin(time * speed)) * height\`
- Gravity arc: \`y = y0 + vy*t - 0.5*g*t*t\`
- Collisions: approximate with simple distance checks
- Particles: use noise functions or trigonometric patterns
- Keep \`useMemo\` computations lightweight — NEVER step a physics world in a loop inside useMemo.

### NEVER use raw WebGLRenderer + useEffect render loops
Do NOT create a \`WebGLRenderer\`, \`Scene\`, or \`Camera\` manually in \`useEffect\`. Use declarative @react-three/fiber JSX instead. Raw Three.js render loops bypass Remotion's frame-accurate rendering and cause memory leaks (creating/destroying the renderer every frame).

### No post-processing
Do NOT import or use: \`@react-three/postprocessing\`, \`EffectComposer\`, \`UnrealBloomPass\`, \`BokehPass\`, \`god-rays\`. They cause artifacts in Remotion renders. Simulate instead with:
- Fog (\`<fog attach="fog" args={[color, near, far]} />\`)
- Emissive materials for glow (\`emissive\`, \`emissiveIntensity\`)
- Transparent spheres for volumetric feel

### Sequence inside ThreeCanvas requires layout="none"
Any \`<Sequence>\` rendered as a child of \`<ThreeCanvas>\` MUST set \`layout="none"\`. The default Sequence wraps children in an \`AbsoluteFill\` \`<div>\`, which is not a valid child of a Three.js scene and will break rendering.
\`\`\`tsx
<ThreeCanvas width={width} height={height}>
  <Sequence from={30} layout="none"><Phase2 /></Sequence>
</ThreeCanvas>
\`\`\`

### Easing: prefer Easing.bezier(), wrappers also valid
\`Easing.bezier(x1, y1, x2, y2)\` matches CSS \`cubic-bezier()\` and is preferred for designer-spec curves. Named wrappers (\`Easing.in\` / \`Easing.out\` / \`Easing.inOut\` over \`Easing.cubic\` | \`quad\` | \`sin\` | \`exp\` | \`circle\`) are also valid Remotion APIs — use whichever reads best.

## Lighting (3-point, recommended)
\`\`\`tsx
<ambientLight color={0x9bb8d4} intensity={0.4} />
<directionalLight
  color={0xfffaea}
  intensity={1.3}
  position={[30, 50, 25]}
  castShadow
  shadow-mapSize-width={2048}
  shadow-mapSize-height={2048}
  shadow-bias={-0.0002}
/>
<hemisphereLight args={[0x87ceeb, 0x3d5c3d, 0.35]} /> {/* fill */}
<directionalLight color={0xffeedd} intensity={0.3} position={[-20, 15, -15]} /> {/* rim, optional */}
\`\`\`

## Materials

- Stylized / Pixar: \`<meshStandardMaterial roughness={0.85} metalness={0} />\`.
- Metal: \`roughness={0.3} metalness={0.8}\`.
- Glass: \`roughness={0.1} metalness={0.2} transparent opacity={0.7}\`.
- Particles: \`<meshBasicMaterial transparent opacity={0.5} />\` (no lighting — much faster).

## Performance budgets (60fps target)
- Total meshes: ≤500. Beyond that, instance.
- Instanced objects: ≤5,000.
- Shadow-casting objects: ≤50.
- Individual particles: ≤200.

## Scene presets (pick when prompt implies one)

- **Outdoor / nature**: sky 0x7ec8e3, horizon 0xd9eaf3, grass 0x7cb87c, sunlight 0xfffaea, fog \`new THREE.FogExp2(0xc5dbe8, 0.015)\`.
- **Sunset / golden hour**: sky 0xff9966, horizon 0xffccaa, sunlight 0xffaa55, exposure 1.3.
- **Night / moonlit**: sky 0x0a1628, moonlight 0xaaccff, fog 0x0a1628, exposure 0.8.
- **Underwater**: water 0x006994, light 0x66ccff, fog density 0.03.

## Animation patterns

- **Looping**: \`const loopTime = (time % loopDuration) / loopDuration;\`
- **Staggered**: \`const itemTime = Math.max(0, time - index * 0.1);\`
- **Spring / bounce**: \`1 - Math.exp(-damping * t) * Math.cos(frequency * t * 2 * Math.PI)\`

## Camera techniques

- **Following**: interpolate a target position over time, position camera offset from it, \`camera.lookAt(target)\` via \`<PerspectiveCamera makeDefault position={[...]} />\` driven by frame.
- **Orbit**: \`position={[Math.cos(time * 0.3) * r, 5, Math.sin(time * 0.3) * r]}\`.
- **Dolly**: interpolate distance over seconds.

### useState/useEffect: allowed ONLY for async audio setup
\`useState\` and \`useEffect\` must NEVER drive animation or per-frame motion. However, they ARE allowed for the \`delayRender\`/\`continueRender\` async-setup pattern (e.g., generating audio with \`Offline\` from \`tone\`). The effect MUST have \`[]\` deps (run once), MUST call \`continueRender()\` when done, and the state MUST NOT drive per-frame motion — only hold static data (audio URL, pre-computed arrays).

### useAudioData takes a STRING, not an object
\`\`\`tsx
const audioData = useAudioData(audioUrl);       // correct — plain string
// const audioData = useAudioData({ src: audioUrl }); // WRONG — causes fetch("[object Object]") → EncodingError
if (!audioData) return <LoadingFallback />;     // always handle null (loading state)
const visualization = visualizeAudio({ audioData, frame, fps, numberOfSamples: 32 });
// visualization is number[] — each value 0..1 representing amplitude at that frequency
\`\`\`

### Tone.js audio synthesis + 3D visualization pattern
When combining Tone.js audio with 3D visuals, \`<Audio>\` and \`useAudioData()\` live in the **outer** default export function (OUTSIDE ThreeCanvas) — they are DOM elements. Compute the \`visualization\` array in the outer component and pass it as a prop to the inner \`<Scene>\` component.

IMPORTANT: \`Sequence\` from \`tone\` conflicts with \`Sequence\` from \`remotion\`. Always rename: \`import { Sequence as ToneSequence } from 'tone'\`.

\`\`\`tsx
import React, { useState, useEffect, useMemo } from 'react';
import { useCurrentFrame, useVideoConfig, interpolate, Easing, AbsoluteFill, Audio, delayRender, continueRender } from 'remotion';
import { ThreeCanvas } from '@remotion/three';
import * as THREE from 'three';
import { useAudioData, visualizeAudio } from '@remotion/media-utils';
import { Offline, Synth } from 'tone';

// Inline WAV encoder — converts an AudioBuffer to a WAV Blob URL
function audioBufferToWav(buffer: AudioBuffer): Blob {
  const numChannels = buffer.numberOfChannels;
  const sampleRate = buffer.sampleRate;
  const bytesPerSample = 2;
  const blockAlign = numChannels * bytesPerSample;
  const data = buffer.getChannelData(0);
  const dataLength = data.length * bytesPerSample;
  const ab = new ArrayBuffer(44 + dataLength);
  const view = new DataView(ab);
  const w = (o: number, s: string) => { for (let i = 0; i < s.length; i++) view.setUint8(o + i, s.charCodeAt(i)); };
  w(0, 'RIFF'); view.setUint32(4, 36 + dataLength, true); w(8, 'WAVE');
  w(12, 'fmt '); view.setUint32(16, 16, true); view.setUint16(20, 1, true);
  view.setUint16(22, numChannels, true); view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * blockAlign, true); view.setUint16(32, blockAlign, true);
  view.setUint16(34, 16, true); w(36, 'data'); view.setUint32(40, dataLength, true);
  let offset = 44;
  for (let i = 0; i < data.length; i++, offset += 2) {
    const s = Math.max(-1, Math.min(1, data[i]));
    view.setInt16(offset, s < 0 ? s * 0x8000 : s * 0x7fff, true);
  }
  return new Blob([ab], { type: 'audio/wav' });
}

// Inner 3D scene — receives visualization data as a prop
const Scene: React.FC<{ visualization: number[] }> = ({ visualization }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const time = frame / fps;

  return (
    <>
      <perspectiveCamera makeDefault position={[0, 3, 8]} fov={50} />
      <ambientLight intensity={0.4} />
      <directionalLight position={[5, 10, 5]} intensity={1.2} />
      {visualization.map((amp, i) => (
        <mesh key={i} position={[i * 0.3 - (visualization.length * 0.15), amp * 2, 0]} scale={[0.2, amp * 4 + 0.1, 0.2]}>
          <boxGeometry args={[1, 1, 1]} />
          <meshStandardMaterial emissive={0x00e5ff} emissiveIntensity={amp * 2} />
        </mesh>
      ))}
    </>
  );
};

// Inner component — only mounts once audioUrl is ready, so useAudioData always gets a valid string.
// This avoids the "useAudioData requires a 'src' parameter" error from passing '' or null.
const VisualizerWithAudio: React.FC<{ audioUrl: string }> = ({ audioUrl }) => {
  const frame = useCurrentFrame();
  const { fps, width, height } = useVideoConfig();
  const audioData = useAudioData(audioUrl);
  if (!audioData) {
    return <AbsoluteFill style={{ backgroundColor: '#000' }} />;
  }
  const visualization = visualizeAudio({ audioData, frame, fps, numberOfSamples: 32 });
  return (
    <AbsoluteFill style={{ backgroundColor: '#0a0a1a' }}>
      <ThreeCanvas width={width} height={height} shadows="variance" resize={{ offsetSize: true }}>
        <Scene visualization={visualization} />
      </ThreeCanvas>
      <Audio src={audioUrl} />
    </AbsoluteFill>
  );
};

// Outer component — handles async audio generation, renders loading until ready.
export default function AudioVisualizer3D() {
  const [handle] = useState(() => delayRender('Generating audio'));
  const [audioUrl, setAudioUrl] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      const buffer = await Offline(({ transport }) => {
        const synth = new Synth().toDestination();
        const notes = ['C4', 'E4', 'G4', 'B4'];
        notes.forEach((note, i) => {
          synth.triggerAttackRelease(note, '8n', i * 0.5);
        });
        transport.start();
      }, 5);

      const wavBlob = audioBufferToWav(buffer.get() as unknown as AudioBuffer);
      setAudioUrl(URL.createObjectURL(wavBlob));
      continueRender(handle);
    })();
  }, []);

  if (!audioUrl) {
    return <AbsoluteFill style={{ backgroundColor: '#000' }} />;
  }

  return <VisualizerWithAudio audioUrl={audioUrl} />;
}
\`\`\`

Key rules for Tone.js + 3D:
- ALWAYS use \`Offline()\` (named import from \`tone\`) — NEVER use the real-time audio context.
- ALWAYS pair with \`delayRender\`/\`continueRender\` — audio generation is async.
- \`<Audio>\` and \`useAudioData\` go OUTSIDE \`<ThreeCanvas>\` (they are DOM elements, not Three.js scene children).
- Pass the \`visualization\` array as a prop to the inner Scene component.
- CRITICAL: \`useAudioData\` requires a valid non-empty string. Because React hooks cannot be called conditionally, use a TWO-COMPONENT pattern: the outer component handles \`delayRender\`/\`continueRender\` and returns a loading screen while \`audioUrl\` is null. Once ready, it renders an inner component that receives \`audioUrl\` as a prop and safely calls \`useAudioData(audioUrl)\`.
- The \`Offline\` callback receives \`({ transport })\` — call \`transport.start()\` to begin.
- Convert ToneAudioBuffer with \`buffer.get() as unknown as AudioBuffer\`.`;

  if (context?.extraInstructions) {
    prompt += `\n\n${context.extraInstructions}`;
  }

  return prompt;
}
