import type { LlmModelDefinition } from './types';

export const LLM_MODEL_CATALOG: LlmModelDefinition[] = [
  // ═══════════════════════════════════════════════════════════════════
  // Tiny models (< 1 GB) — good for testing & low-end hardware
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'smollm2-360m-q8',
    name: 'SmolLM2 360M Instruct',
    family: 'smollm2',
    parameterCount: '360M',
    quantization: 'Q8_0',
    contextLength: 2048,
    sizeBytes: 386_000_000,
    sizeLabel: '386 MB',
    downloadUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct-GGUF/resolve/main/smollm2-360m-instruct-q8_0.gguf',
    fileName: 'smollm2-360m-instruct-q8_0.gguf',
    description: 'Ultra-lightweight model for simple text tasks and testing',
    capabilities: [],
    releaseDate: '2024-11',
  },

  {
    id: 'qwen2.5-0.5b-q8',
    name: 'Qwen 2.5 0.5B Instruct',
    family: 'qwen2.5',
    parameterCount: '0.5B',
    quantization: 'Q8_0',
    contextLength: 32768,
    sizeBytes: 531_000_000,
    sizeLabel: '531 MB',
    downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q8_0.gguf',
    fileName: 'qwen2.5-0.5b-instruct-q8_0.gguf',
    description: 'Tiny but capable general model with 32K context',
    capabilities: ['multilingual'],
    releaseDate: '2024-09',
  },

  {
    id: 'qwen3.5-0.8b-q8',
    name: 'Qwen 3.5 0.8B',
    family: 'qwen3.5',
    parameterCount: '0.8B',
    quantization: 'Q8_0',
    contextLength: 262144,
    sizeBytes: 812_000_000,
    sizeLabel: '812 MB',
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF/resolve/main/Qwen3.5-0.8B-Q8_0.gguf',
    fileName: 'Qwen3.5-0.8B-Q8_0.gguf',
    description: 'Latest-gen Qwen with massive 256K context at tiny size',
    capabilities: ['multilingual'],
    releaseDate: '2025-06',
  },

  // ═══════════════════════════════════════════════════════════════════
  // Small models (1–2 GB)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'gemma-3-1b-q8',
    name: 'Gemma 3 1B Instruct',
    family: 'gemma-3',
    parameterCount: '1B',
    quantization: 'Q8_0',
    contextLength: 32768,
    sizeBytes: 1_070_000_000,
    sizeLabel: '1.07 GB',
    downloadUrl: 'https://huggingface.co/ggml-org/gemma-3-1b-it-GGUF/resolve/main/gemma-3-1b-it-Q8_0.gguf',
    fileName: 'gemma-3-1b-it-Q8_0.gguf',
    description: 'Google\'s latest tiny model, strong for its size',
    capabilities: ['multilingual'],
    releaseDate: '2025-03',
  },

  {
    id: 'llama-3.2-1b-q8',
    name: 'Llama 3.2 1B Instruct',
    family: 'llama-3.2',
    parameterCount: '1.2B',
    quantization: 'Q8_0',
    contextLength: 131072,
    sizeBytes: 1_300_000_000,
    sizeLabel: '1.3 GB',
    downloadUrl: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q8_0.gguf',
    fileName: 'Llama-3.2-1B-Instruct-Q8_0.gguf',
    description: 'Meta\'s lightweight model with 128K context window',
    capabilities: ['multilingual'],
    releaseDate: '2024-09',
  },

  {
    id: 'qwen2.5-1.5b-q4km',
    name: 'Qwen 2.5 1.5B Instruct',
    family: 'qwen2.5',
    parameterCount: '1.5B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 986_000_000,
    sizeLabel: '986 MB',
    downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf',
    fileName: 'qwen2.5-1.5b-instruct-q4_k_m.gguf',
    description: 'Solid general-purpose small model with multilingual support',
    capabilities: ['multilingual'],
    releaseDate: '2024-09',
  },

  {
    id: 'qwen2.5-coder-1.5b-q4km',
    name: 'Qwen 2.5 Coder 1.5B Instruct',
    family: 'qwen2.5-coder',
    parameterCount: '1.5B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 1_120_000_000,
    sizeLabel: '1.12 GB',
    downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF/resolve/main/qwen2.5-coder-1.5b-instruct-q4_k_m.gguf',
    fileName: 'qwen2.5-coder-1.5b-instruct-q4_k_m.gguf',
    description: 'Code-specialized tiny model for scripting and generation',
    capabilities: ['coding'],
    releaseDate: '2024-11',
  },

  {
    id: 'deepseek-r1-distill-1.5b-q4km',
    name: 'DeepSeek R1 Distill Qwen 1.5B',
    family: 'deepseek-r1',
    parameterCount: '1.5B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 1_120_000_000,
    sizeLabel: '1.12 GB',
    downloadUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-1.5B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf',
    fileName: 'DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf',
    description: 'Reasoning-focused distill with chain-of-thought capability',
    capabilities: ['reasoning'],
    releaseDate: '2025-01',
  },

  {
    id: 'qwen3.5-2b-q4km',
    name: 'Qwen 3.5 2B',
    family: 'qwen3.5',
    parameterCount: '2B',
    quantization: 'Q4_K_M',
    contextLength: 262144,
    sizeBytes: 1_280_000_000,
    sizeLabel: '1.28 GB',
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-2B-GGUF/resolve/main/Qwen3.5-2B-Q4_K_M.gguf',
    fileName: 'Qwen3.5-2B-Q4_K_M.gguf',
    description: 'Latest-gen Qwen with 256K context, great general performance',
    capabilities: ['multilingual'],
    releaseDate: '2025-06',
  },

  {
    id: 'smollm2-1.7b-q4km',
    name: 'SmolLM2 1.7B Instruct',
    family: 'smollm2',
    parameterCount: '1.7B',
    quantization: 'Q4_K_M',
    contextLength: 8192,
    sizeBytes: 1_060_000_000,
    sizeLabel: '1.0 GB',
    downloadUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF/resolve/main/smollm2-1.7b-instruct-q4_k_m.gguf',
    fileName: 'smollm2-1.7b-instruct-q4_k_m.gguf',
    description: 'HuggingFace\'s efficient small model for simple tasks',
    capabilities: [],
    releaseDate: '2024-11',
  },

  {
    id: 'gemma-2-2b-q4km',
    name: 'Gemma 2 2B Instruct',
    family: 'gemma-2',
    parameterCount: '2.6B',
    quantization: 'Q4_K_M',
    contextLength: 8192,
    sizeBytes: 1_600_000_000,
    sizeLabel: '1.6 GB',
    downloadUrl: 'https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q4_K_M.gguf',
    fileName: 'gemma-2-2b-it-Q4_K_M.gguf',
    description: 'Google\'s previous-gen small model, solid reasoning',
    capabilities: ['multilingual'],
    releaseDate: '2024-06',
  },

  // ═══════════════════════════════════════════════════════════════════
  // Medium models (2–3 GB)
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'llama-3.2-3b-q4km',
    name: 'Llama 3.2 3B Instruct',
    family: 'llama-3.2',
    parameterCount: '3.2B',
    quantization: 'Q4_K_M',
    contextLength: 131072,
    sizeBytes: 2_020_000_000,
    sizeLabel: '2.0 GB',
    downloadUrl: 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf',
    fileName: 'Llama-3.2-3B-Instruct-Q4_K_M.gguf',
    description: 'Meta\'s versatile 3B model with 128K context',
    capabilities: ['multilingual'],
    releaseDate: '2024-09',
  },

  {
    id: 'phi-3.5-mini-q4km',
    name: 'Phi-3.5 Mini Instruct',
    family: 'phi-3.5',
    parameterCount: '3.8B',
    quantization: 'Q4_K_M',
    contextLength: 131072,
    sizeBytes: 2_390_000_000,
    sizeLabel: '2.3 GB',
    downloadUrl: 'https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q4_K_M.gguf',
    fileName: 'Phi-3.5-mini-instruct-Q4_K_M.gguf',
    description: 'Microsoft\'s compact model, strong on math and reasoning',
    capabilities: ['reasoning', 'multilingual'],
    releaseDate: '2024-08',
  },

  {
    id: 'phi-4-mini-q4km',
    name: 'Phi-4 Mini Instruct',
    family: 'phi-4',
    parameterCount: '3.8B',
    quantization: 'Q4_K_M',
    contextLength: 131072,
    sizeBytes: 2_490_000_000,
    sizeLabel: '2.49 GB',
    downloadUrl: 'https://huggingface.co/bartowski/microsoft_Phi-4-mini-instruct-GGUF/resolve/main/microsoft_Phi-4-mini-instruct-Q4_K_M.gguf',
    fileName: 'microsoft_Phi-4-mini-instruct-Q4_K_M.gguf',
    description: 'Microsoft\'s latest mini — beats GPT-4o on math benchmarks',
    capabilities: ['reasoning', 'coding', 'multilingual'],
    releaseDate: '2025-02',
  },

  {
    id: 'gemma-3-4b-q4km',
    name: 'Gemma 3 4B Instruct',
    family: 'gemma-3',
    parameterCount: '4B',
    quantization: 'Q4_K_M',
    contextLength: 128000,
    sizeBytes: 2_490_000_000,
    sizeLabel: '2.49 GB',
    downloadUrl: 'https://huggingface.co/ggml-org/gemma-3-4b-it-GGUF/resolve/main/gemma-3-4b-it-Q4_K_M.gguf',
    fileName: 'gemma-3-4b-it-Q4_K_M.gguf',
    description: 'Google\'s latest with 128K context and vision support',
    capabilities: ['vision', 'multilingual'],
    releaseDate: '2025-03',
  },

  {
    id: 'qwen3.5-4b-q4km',
    name: 'Qwen 3.5 4B',
    family: 'qwen3.5',
    parameterCount: '4B',
    quantization: 'Q4_K_M',
    contextLength: 262144,
    sizeBytes: 2_740_000_000,
    sizeLabel: '2.74 GB',
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/Qwen3.5-4B-Q4_K_M.gguf',
    fileName: 'Qwen3.5-4B-Q4_K_M.gguf',
    description: 'Best general model at 4B size, 256K context window',
    capabilities: ['multilingual'],
    releaseDate: '2025-06',
  },

  {
    id: 'qwen2.5-3b-q4km',
    name: 'Qwen 2.5 3B Instruct',
    family: 'qwen2.5',
    parameterCount: '3.1B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 1_930_000_000,
    sizeLabel: '1.9 GB',
    downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf',
    fileName: 'qwen2.5-3b-instruct-q4_k_m.gguf',
    description: 'Reliable general-purpose model with strong multilingual support',
    capabilities: ['multilingual'],
    releaseDate: '2024-09',
  },

  // ═══════════════════════════════════════════════════════════════════
  // Large models (4–5 GB) — needs good GPU or 16+ GB RAM
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'qwen2.5-7b-q4km',
    name: 'Qwen 2.5 7B Instruct',
    family: 'qwen2.5',
    parameterCount: '7.6B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 4_680_000_000,
    sizeLabel: '4.7 GB',
    downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-7B-Instruct-GGUF/resolve/main/qwen2.5-7b-instruct-q4_k_m.gguf',
    fileName: 'qwen2.5-7b-instruct-q4_k_m.gguf',
    description: 'Strong all-rounder at 7B, great quality-to-size ratio',
    capabilities: ['multilingual'],
    releaseDate: '2024-09',
  },

  {
    id: 'qwen2.5-coder-7b-q4km',
    name: 'Qwen 2.5 Coder 7B Instruct',
    family: 'qwen2.5-coder',
    parameterCount: '7B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 4_680_000_000,
    sizeLabel: '4.68 GB',
    downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/qwen2.5-coder-7b-instruct-q4_k_m.gguf',
    fileName: 'qwen2.5-coder-7b-instruct-q4_k_m.gguf',
    description: 'Top coding model at 7B — ideal for TSX and script generation',
    capabilities: ['coding'],
    releaseDate: '2024-11',
  },

  {
    id: 'deepseek-r1-distill-7b-q4km',
    name: 'DeepSeek R1 Distill Qwen 7B',
    family: 'deepseek-r1',
    parameterCount: '7B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 4_680_000_000,
    sizeLabel: '4.68 GB',
    downloadUrl: 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf',
    fileName: 'DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf',
    description: 'Strong reasoning with chain-of-thought at 7B size',
    capabilities: ['reasoning'],
    releaseDate: '2025-01',
  },

  {
    id: 'llama-3.1-8b-q4km',
    name: 'Llama 3.1 8B Instruct',
    family: 'llama-3.1',
    parameterCount: '8.0B',
    quantization: 'Q4_K_M',
    contextLength: 131072,
    sizeBytes: 4_920_000_000,
    sizeLabel: '4.9 GB',
    downloadUrl: 'https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    fileName: 'Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    description: 'Meta\'s workhorse 8B model with 128K context',
    capabilities: ['coding', 'multilingual'],
    releaseDate: '2024-07',
  },

  // ═══════════════════════════════════════════════════════════════════
  // Extra-large models (5–10 GB) — needs 16+ GB RAM or good GPU
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'qwen3.5-9b-q4km',
    name: 'Qwen 3.5 9B',
    family: 'qwen3.5',
    parameterCount: '9B',
    quantization: 'Q4_K_M',
    contextLength: 262144,
    sizeBytes: 5_680_000_000,
    sizeLabel: '5.68 GB',
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-9B-GGUF/resolve/main/Qwen3.5-9B-Q4_K_M.gguf',
    fileName: 'Qwen3.5-9B-Q4_K_M.gguf',
    description: 'Latest-gen Qwen 9B with vision and 256K context',
    capabilities: ['vision', 'multilingual'],
    releaseDate: '2025-06',
  },

  {
    id: 'gemma-3-12b-q4km',
    name: 'Gemma 3 12B Instruct',
    family: 'gemma-3',
    parameterCount: '12B',
    quantization: 'Q4_K_M',
    contextLength: 128000,
    sizeBytes: 7_300_000_000,
    sizeLabel: '7.3 GB',
    downloadUrl: 'https://huggingface.co/unsloth/gemma-3-12b-it-GGUF/resolve/main/gemma-3-12b-it-Q4_K_M.gguf',
    fileName: 'gemma-3-12b-it-Q4_K_M.gguf',
    description: 'Google\'s best mid-size model with vision and 128K context',
    capabilities: ['vision', 'coding', 'multilingual'],
    releaseDate: '2025-03',
  },

  {
    id: 'mistral-nemo-12b-q4km',
    name: 'Mistral Nemo 12B Instruct',
    family: 'mistral',
    parameterCount: '12B',
    quantization: 'Q4_K_M',
    contextLength: 128000,
    sizeBytes: 7_480_000_000,
    sizeLabel: '7.48 GB',
    downloadUrl: 'https://huggingface.co/bartowski/Mistral-Nemo-Instruct-2407-GGUF/resolve/main/Mistral-Nemo-Instruct-2407-Q4_K_M.gguf',
    fileName: 'Mistral-Nemo-Instruct-2407-Q4_K_M.gguf',
    description: 'Mistral + Nvidia collab, great for conversation and coding',
    capabilities: ['coding', 'multilingual'],
    releaseDate: '2024-07',
  },

  {
    id: 'qwen2.5-14b-q4km',
    name: 'Qwen 2.5 14B Instruct',
    family: 'qwen2.5',
    parameterCount: '14B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 8_990_000_000,
    sizeLabel: '8.99 GB',
    downloadUrl: 'https://huggingface.co/bartowski/Qwen2.5-14B-Instruct-GGUF/resolve/main/Qwen2.5-14B-Instruct-Q4_K_M.gguf',
    fileName: 'Qwen2.5-14B-Instruct-Q4_K_M.gguf',
    description: 'High-quality general model, excellent for complex tasks',
    capabilities: ['coding', 'multilingual'],
    releaseDate: '2024-09',
  },

  {
    id: 'deepseek-r1-distill-14b-q4km',
    name: 'DeepSeek R1 Distill Qwen 14B',
    family: 'deepseek-r1',
    parameterCount: '14B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 8_990_000_000,
    sizeLabel: '8.99 GB',
    downloadUrl: 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-14B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf',
    fileName: 'DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf',
    description: 'Powerful reasoning model, strong on math and logic at 14B',
    capabilities: ['reasoning', 'coding'],
    releaseDate: '2025-01',
  },

  {
    id: 'phi-4-q4km',
    name: 'Phi-4 Instruct',
    family: 'phi-4',
    parameterCount: '14B',
    quantization: 'Q4_K_M',
    contextLength: 16384,
    sizeBytes: 9_050_000_000,
    sizeLabel: '9.05 GB',
    downloadUrl: 'https://huggingface.co/bartowski/phi-4-GGUF/resolve/main/phi-4-Q4_K_M.gguf',
    fileName: 'phi-4-Q4_K_M.gguf',
    description: 'Microsoft\'s best — exceptional reasoning, math, and coding',
    capabilities: ['reasoning', 'coding', 'multilingual'],
    releaseDate: '2024-12',
  },

  // ═══════════════════════════════════════════════════════════════════
  // Huge models (10–20 GB) — needs 24+ GB RAM or 16+ GB VRAM
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'mistral-small-24b-q4km',
    name: 'Mistral Small 24B Instruct',
    family: 'mistral',
    parameterCount: '24B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 14_330_000_000,
    sizeLabel: '14.33 GB',
    downloadUrl: 'https://huggingface.co/bartowski/Mistral-Small-24B-Instruct-2501-GGUF/resolve/main/Mistral-Small-24B-Instruct-2501-Q4_K_M.gguf',
    fileName: 'Mistral-Small-24B-Instruct-2501-Q4_K_M.gguf',
    description: 'Mistral\'s efficient 24B, strong across all tasks',
    capabilities: ['coding', 'multilingual'],
    releaseDate: '2025-01',
  },

  {
    id: 'gemma-3-27b-q4km',
    name: 'Gemma 3 27B Instruct',
    family: 'gemma-3',
    parameterCount: '27B',
    quantization: 'Q4_K_M',
    contextLength: 128000,
    sizeBytes: 16_500_000_000,
    sizeLabel: '16.5 GB',
    downloadUrl: 'https://huggingface.co/unsloth/gemma-3-27b-it-GGUF/resolve/main/gemma-3-27b-it-Q4_K_M.gguf',
    fileName: 'gemma-3-27b-it-Q4_K_M.gguf',
    description: 'Google\'s flagship open model with vision and 128K context',
    capabilities: ['vision', 'coding', 'reasoning', 'multilingual'],
    releaseDate: '2025-03',
  },

  {
    id: 'deepseek-r1-distill-32b-q4km',
    name: 'DeepSeek R1 Distill Qwen 32B',
    family: 'deepseek-r1',
    parameterCount: '32B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 19_850_000_000,
    sizeLabel: '19.85 GB',
    downloadUrl: 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-32B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf',
    fileName: 'DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf',
    description: 'Outperforms OpenAI o1-mini on reasoning benchmarks',
    capabilities: ['reasoning', 'coding'],
    releaseDate: '2025-01',
  },

  {
    id: 'qwen2.5-coder-32b-q4km',
    name: 'Qwen 2.5 Coder 32B Instruct',
    family: 'qwen2.5-coder',
    parameterCount: '32B',
    quantization: 'Q4_K_M',
    contextLength: 32768,
    sizeBytes: 19_900_000_000,
    sizeLabel: '19.9 GB',
    downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct-GGUF/resolve/main/qwen2.5-coder-32b-instruct-q4_k_m.gguf',
    fileName: 'qwen2.5-coder-32b-instruct-q4_k_m.gguf',
    description: 'Best open-source coding model — rivals GPT-4 on code tasks',
    capabilities: ['coding'],
    releaseDate: '2024-11',
  },

  // ═══════════════════════════════════════════════════════════════════
  // Massive models (40+ GB) — needs 48+ GB RAM or multi-GPU
  // ═══════════════════════════════════════════════════════════════════

  {
    id: 'llama-3.3-70b-q4km',
    name: 'Llama 3.3 70B Instruct',
    family: 'llama-3.3',
    parameterCount: '70B',
    quantization: 'Q4_K_M',
    contextLength: 131072,
    sizeBytes: 42_520_000_000,
    sizeLabel: '42.52 GB',
    downloadUrl: 'https://huggingface.co/bartowski/Llama-3.3-70B-Instruct-GGUF/resolve/main/Llama-3.3-70B-Instruct-Q4_K_M.gguf',
    fileName: 'Llama-3.3-70B-Instruct-Q4_K_M.gguf',
    description: 'Meta\'s flagship — competitive with GPT-4o across all tasks',
    capabilities: ['coding', 'reasoning', 'multilingual'],
    releaseDate: '2024-12',
  },
];
