// Reading a `.vidtsxflow` file (flows plan §1.7, §0.1 item 4, W8 Stage 6).
//
// The agents' three layers, parameterised by manifest name:
//   1. `zip-reader.ts` guarantees the container (caps, no duplicates,
//      manifest-as-allowlist, declared == actual, hash on every extracted byte).
//   2. `parseFlowPackageManifest` decides whether `flow.json` is acceptable
//      given what THIS build knows — pure, so `flow-pack.mjs --check` runs
//      the identical rules offline.
//   3. This file joins the two and adds the signature: `signature.json` over
//      the canonical JSON of `flow.json`, verified by the SAME
//      `agent-signing.ts` module and the same publisher list (decision 10:
//      one signing module, two manifest names).
//
// No D14 gate: a flow package carries no TSX. Its `assets/` are reference
// media the nodes may point at; a composition a flow makes is generated by a
// tool at run time and gated there.

import {
  openZipPackage,
  PackageReadError,
  type ExtractProgress,
  type OpenedZipPackage,
  type ZipReaderSpec,
} from '../packages/zip-reader';
import {
  FLOW_LIMITS,
  FLOW_MANIFEST_NAME,
  FlowManifestError,
  parseFlowPackageManifest,
  type FlowManifestContext,
  type FlowPackageManifest,
} from '../../../shared/flows/flow-package';
import type { AgentPublisher } from '../../../shared/agents/publishers';
import {
  AGENT_LICENSEE_NAME,
  AGENT_SIDE_FILE_MAX_BYTES,
  AGENT_SIGNATURE_NAME,
  AgentSignatureError,
  parseLicenseeFile,
  parseSignatureFile,
  verifyAgentSignature,
  type AgentLicensee,
  type SignatureOutcome,
} from '../agents/agent-signing';

export { PackageReadError };

export interface FlowPackageDeps {
  manifestContext: FlowManifestContext;
  /** Overridable for tests; defaults to the shipped publisher list. */
  publishers?: readonly AgentPublisher[];
}

export interface OpenedFlowPackage {
  manifest: FlowPackageManifest;
  /** `flow.json` byte for byte — the installed folder needs these exact
   *  bytes, or the signature stops verifying on the next scan. */
  manifestBytes: Buffer;
  signature: SignatureOutcome;
  licensee?: AgentLicensee;
  read(entryPath: string): Promise<Buffer>;
  extractAll(destRoot: string, onProgress?: (p: ExtractProgress) => void): Promise<void>;
  /** `signature.json` / `licensee.json` as they arrived, written verbatim on install. */
  sideFiles: Array<{ name: string; body: Buffer }>;
}

function flowSpec(ctx: FlowManifestContext): ZipReaderSpec<FlowPackageManifest> {
  return {
    manifestName: FLOW_MANIFEST_NAME,
    parseManifest(raw) {
      try {
        return parseFlowPackageManifest(raw, ctx);
      } catch (err) {
        if (err instanceof FlowManifestError) {
          throw new PackageReadError(
            `This flow package cannot be installed:\n${err.problems.map((p) => `• ${p}`).join('\n')}`,
          );
        }
        throw err;
      }
    },
    filesOf: (manifest) => manifest.files,
    unlistedEntries: [AGENT_SIGNATURE_NAME, AGENT_LICENSEE_NAME],
    limits: {
      maxEntries: FLOW_LIMITS.maxEntries,
      maxManifestBytes: FLOW_LIMITS.maxManifestBytes,
      maxReadBytes: FLOW_LIMITS.maxEntryBytes,
      maxEntryBytes: FLOW_LIMITS.maxEntryBytes,
      maxTotalBytes: FLOW_LIMITS.maxTotalBytes,
    },
    notReadableMessage: 'This file is not a readable .vidtsxflow package.',
  };
}

async function readSideFile(
  zip: OpenedZipPackage<FlowPackageManifest>,
  name: string,
): Promise<{ raw: unknown; body: Buffer } | null> {
  const body = await zip.readUnlisted(name, AGENT_SIDE_FILE_MAX_BYTES);
  if (!body) return null;
  try {
    return { raw: JSON.parse(body.toString('utf-8')) as unknown, body };
  } catch {
    throw new PackageReadError(`The package ${name} is not readable JSON.`);
  }
}

/**
 * Open and fully validate a flow package WITHOUT writing anything. A
 * tampered manifest (a byte changed after signing) throws here, before an
 * install has touched the disk — the signature no longer matches.
 */
export async function openFlowPackage(filePath: string, deps: FlowPackageDeps): Promise<OpenedFlowPackage> {
  const zip = await openZipPackage(filePath, flowSpec(deps.manifestContext));
  const sideFiles: Array<{ name: string; body: Buffer }> = [];

  const signatureFile = await readSideFile(zip, AGENT_SIGNATURE_NAME);
  let signature: SignatureOutcome;
  if (signatureFile) {
    const parsed = parseSignatureFile(signatureFile.raw);
    if (!parsed) throw new PackageReadError('The package signature.json is not a signature this app reads.');
    try {
      signature = verifyAgentSignature(zip.rawManifest, parsed, deps.publishers);
    } catch (err) {
      throw err instanceof AgentSignatureError ? new PackageReadError(err.message) : err;
    }
    sideFiles.push({ name: AGENT_SIGNATURE_NAME, body: signatureFile.body });
  } else {
    signature = { status: 'unsigned' };
  }

  const licenseeFile = await readSideFile(zip, AGENT_LICENSEE_NAME);
  const licensee = licenseeFile ? (parseLicenseeFile(licenseeFile.raw) ?? undefined) : undefined;
  if (licenseeFile && licensee) sideFiles.push({ name: AGENT_LICENSEE_NAME, body: licenseeFile.body });

  return {
    manifest: zip.manifest,
    manifestBytes: zip.manifestBytes,
    signature,
    licensee,
    read: zip.read,
    extractAll: zip.extractAll,
    sideFiles,
  };
}
