import fs from 'fs/promises';
import path from 'path';
import { logEngine } from '../../../logging/log-engine';
import type { StudioMediaJobEvent, StudioMediaJobKind } from '../../../shared/ipc/types/studio';
import { getProjectCacheDir } from './studio-paths';
import { generateProxy, proxyRelPath } from './proxy-generator';
import { generateWaveform, waveformRelPath } from './waveform-generator';

const log = logEngine.createLogger('StudioMediaJobs');

interface JobRecord {
  id: string;
  projectId: string;
  assetId: string;
  kind: StudioMediaJobKind;
  sourcePath: string;
  abort: AbortController;
  running: boolean;
}

function relPathFor(kind: StudioMediaJobKind, assetId: string): string {
  return kind === 'proxy' ? proxyRelPath(assetId) : waveformRelPath(assetId);
}

/**
 * Background proxy/waveform generation, modeled on the TSX job engine: id-keyed
 * records, a concurrency throttle, per-job abort, and a broadcast stream the
 * renderer folds back into the project document.
 *
 * Nothing is persisted across restarts on purpose — every job is re-derivable
 * from the document plus what is already on disk in cache/, so the editor just
 * re-requests what is missing when a project opens.
 */
class StudioMediaJobEngine {
  private jobs = new Map<string, JobRecord>();
  private listeners = new Set<(event: StudioMediaJobEvent) => void>();
  /** ffmpeg saturates cores quickly; two at a time keeps the app responsive. */
  private maxConcurrent = 2;
  private shuttingDown = false;

  onEvent(listener: (event: StudioMediaJobEvent) => void): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  /** Queue a job unless the output already exists or the same job is pending. */
  async request(
    projectId: string,
    assetId: string,
    kind: StudioMediaJobKind,
    sourcePath: string,
  ): Promise<StudioMediaJobEvent | null> {
    if (this.shuttingDown) return null;
    const id = `${projectId}:${assetId}:${kind}`;
    if (this.jobs.has(id)) return null;

    const relPath = relPathFor(kind, assetId);
    const cacheDir = await getProjectCacheDir(projectId);
    try {
      const stat = await fs.stat(path.join(cacheDir, relPath));
      if (stat.size > 0) {
        // Already generated by an earlier session — report it so the document
        // picks the status up without spending another ffmpeg pass.
        const event: StudioMediaJobEvent = {
          projectId,
          assetId,
          kind,
          status: 'ready',
          relPath,
        };
        this.emit(event);
        return event;
      }
    } catch {
      // Not generated yet — fall through and queue it.
    }

    this.jobs.set(id, {
      id,
      projectId,
      assetId,
      kind,
      sourcePath,
      abort: new AbortController(),
      running: false,
    });
    this.emit({ projectId, assetId, kind, status: 'generating' });
    this.pump();
    return null;
  }

  /** Abort everything belonging to a project (the editor closed). */
  cancelProject(projectId: string): void {
    for (const [id, job] of this.jobs) {
      if (job.projectId !== projectId) continue;
      job.abort.abort();
      if (!job.running) this.jobs.delete(id);
    }
  }

  shutdown(): void {
    this.shuttingDown = true;
    for (const job of this.jobs.values()) job.abort.abort();
    this.jobs.clear();
  }

  private emit(event: StudioMediaJobEvent): void {
    for (const listener of this.listeners) {
      try {
        listener(event);
      } catch {
        // A failing listener must not stall the queue.
      }
    }
  }

  private runningCount(): number {
    let count = 0;
    for (const job of this.jobs.values()) if (job.running) count++;
    return count;
  }

  private pump(): void {
    if (this.shuttingDown) return;
    while (this.runningCount() < this.maxConcurrent) {
      const next = [...this.jobs.values()].find((j) => !j.running);
      if (!next) return;
      next.running = true;
      void this.run(next);
    }
  }

  private async run(job: JobRecord): Promise<void> {
    try {
      const relPath =
        job.kind === 'proxy'
          ? await generateProxy(job.projectId, job.assetId, job.sourcePath, job.abort.signal)
          : await generateWaveform(job.projectId, job.assetId, job.sourcePath, job.abort.signal);
      this.jobs.delete(job.id);
      if (job.abort.signal.aborted) return;
      this.emit({
        projectId: job.projectId,
        assetId: job.assetId,
        kind: job.kind,
        status: 'ready',
        relPath,
      });
    } catch (err) {
      this.jobs.delete(job.id);
      if (job.abort.signal.aborted) return;
      const message = err instanceof Error ? err.message : String(err);
      log.warn('Media job failed', { job: job.id, error: message.slice(0, 300) });
      this.emit({
        projectId: job.projectId,
        assetId: job.assetId,
        kind: job.kind,
        status: 'error',
        error: message.slice(0, 300),
      });
    } finally {
      this.pump();
    }
  }
}

export const studioMediaJobs = new StudioMediaJobEngine();
