import fs from 'fs/promises';
import path from 'path';
import { logEngine } from '../../../logging/log-engine';
import type { StudioMediaJobEvent, StudioMediaJobKind } from '../../../shared/ipc/types/studio';
import { getProjectCacheDir } from './studio-paths';
import { generateProxy, proxyRelPath } from './proxy-generator';
import { generateWaveform, waveformRelPath } from './waveform-generator';
import { readTranscriptMeta, transcribeAsset, transcriptRelPath } from './asset-transcriber';
import { analysisRelPath, analysisSatisfying, isAnalysisKind, runAnalysisJob, type AnalysisJobOptions } from './analysis-jobs';
import { analysisEngine } from '../../../analysis-engine/analysis-engine';

const log = logEngine.createLogger('StudioMediaJobs');

interface JobRecord {
  id: string;
  projectId: string;
  assetId: string;
  kind: StudioMediaJobKind;
  sourcePath: string;
  /** Transcript jobs: which STT catalog model to run. */
  sttModelId?: string;
  /** Analysis jobs (`faceTrack`, `subjectMask`): the spans, fps and frame source. */
  analysis?: AnalysisJobOptions;
  abort: AbortController;
  running: boolean;
}

function relPathFor(kind: StudioMediaJobKind, assetId: string): string {
  if (kind === 'proxy') return proxyRelPath(assetId);
  if (kind === 'waveform') return waveformRelPath(assetId);
  if (isAnalysisKind(kind)) return analysisRelPath(kind, assetId);
  return transcriptRelPath(assetId);
}

export interface MediaJobRequestOptions {
  /** Transcript jobs: STT catalog model id. */
  sttModelId?: string;
  /** Re-run even when output already exists (explicit re-transcribe). */
  force?: boolean;
  /** Analysis jobs: what to analyse. Required for `faceTrack` / `subjectMask`. */
  analysis?: AnalysisJobOptions;
}

/**
 * Background proxy/waveform/transcript generation, modeled on the TSX job
 * engine: id-keyed records, a concurrency throttle, per-job abort, and a
 * broadcast stream the renderer folds back into the project document.
 *
 * Nothing is persisted across restarts on purpose — every job is re-derivable
 * from the document plus what is already on disk in cache/, so the editor just
 * re-requests what is missing when a project opens. (Transcripts are never
 * auto-requested — they only run from an explicit user action.)
 */
class StudioMediaJobEngine {
  private jobs = new Map<string, JobRecord>();
  private listeners = new Set<(event: StudioMediaJobEvent) => void>();
  /** ffmpeg saturates cores quickly; two at a time keeps the app responsive. */
  private maxConcurrent = 2;
  private shuttingDown = false;

  onEvent(listener: (event: StudioMediaJobEvent) => void): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  /** Queue a job unless the output already exists or the same job is pending. */
  async request(
    projectId: string,
    assetId: string,
    kind: StudioMediaJobKind,
    sourcePath: string,
    options: MediaJobRequestOptions = {},
  ): Promise<StudioMediaJobEvent | null> {
    if (this.shuttingDown) return null;
    const id = `${projectId}:${assetId}:${kind}`;
    if (this.jobs.has(id)) return null;

    const relPath = relPathFor(kind, assetId);
    if (isAnalysisKind(kind)) {
      // Span-aware: the cached track counts as ready only when it covers the
      // spans asked for (an extended clip queues the job for the new seconds).
      if (!options.analysis) throw new Error('Analysis job queued without its spans');
      const satisfied = await analysisSatisfying(projectId, assetId, kind, options.analysis);
      if (satisfied) {
        const event: StudioMediaJobEvent = { projectId, assetId, kind, status: 'ready', relPath, analysis: satisfied.analysis };
        this.emit(event);
        return event;
      }
    } else if (!options.force) {
      const cacheDir = await getProjectCacheDir(projectId);
      try {
        const stat = await fs.stat(path.join(cacheDir, relPath));
        if (stat.size > 0) {
          // Already generated by an earlier session — report it so the document
          // picks the status up without spending another pass.
          const event: StudioMediaJobEvent = {
            projectId,
            assetId,
            kind,
            status: 'ready',
            relPath,
            ...(kind === 'transcript'
              ? { transcript: (await readTranscriptMeta(projectId, assetId)) ?? undefined }
              : {}),
          };
          this.emit(event);
          return event;
        }
      } catch {
        // Not generated yet — fall through and queue it.
      }
    }

    this.jobs.set(id, {
      id,
      projectId,
      assetId,
      kind,
      sourcePath,
      sttModelId: options.sttModelId,
      analysis: options.analysis,
      abort: new AbortController(),
      running: false,
    });
    this.emit({ projectId, assetId, kind, status: 'generating' });
    this.pump();
    return null;
  }

  /** Abort one job (the user canceled it) and tell the renderer. */
  cancel(projectId: string, assetId: string, kind: StudioMediaJobKind): boolean {
    const id = `${projectId}:${assetId}:${kind}`;
    const job = this.jobs.get(id);
    if (!job) return false;
    job.abort.abort();
    if (!job.running) this.jobs.delete(id);
    this.emit({ projectId, assetId, kind, status: 'canceled' });
    return true;
  }

  /** Abort everything belonging to a project (the editor closed). */
  cancelProject(projectId: string): void {
    for (const [id, job] of this.jobs) {
      if (job.projectId !== projectId) continue;
      job.abort.abort();
      if (!job.running) this.jobs.delete(id);
    }
  }

  shutdown(): void {
    this.shuttingDown = true;
    for (const job of this.jobs.values()) job.abort.abort();
    this.jobs.clear();
  }

  private emit(event: StudioMediaJobEvent): void {
    for (const listener of this.listeners) {
      try {
        listener(event);
      } catch {
        // A failing listener must not stall the queue.
      }
    }
  }

  private runningCount(): number {
    let count = 0;
    for (const job of this.jobs.values()) if (job.running) count++;
    return count;
  }

  /** Jobs that must run alone: transcripts by kind, the two analysis kinds as one group (one worker). */
  private exclusiveRunning(kind: StudioMediaJobKind): boolean {
    for (const job of this.jobs.values()) {
      if (!job.running) continue;
      if (job.kind === kind || (isAnalysisKind(kind) && isAnalysisKind(job.kind))) return true;
    }
    return false;
  }

  private pump(): void {
    if (this.shuttingDown) return;
    while (this.runningCount() < this.maxConcurrent) {
      // Transcript jobs run one at a time: whisper is CPU-heavy and the
      // whisper service tracks a single active child process. Analysis jobs
      // too: one worker process, one frame at a time.
      const next = [...this.jobs.values()].find(
        (j) => !j.running && ((j.kind !== 'transcript' && !isAnalysisKind(j.kind)) || !this.exclusiveRunning(j.kind)),
      );
      if (!next) return;
      next.running = true;
      void this.run(next);
    }
  }

  private async run(job: JobRecord): Promise<void> {
    try {
      const event = await this.produce(job);
      this.jobs.delete(job.id);
      if (job.abort.signal.aborted) return;
      this.emit(event);
    } catch (err) {
      this.jobs.delete(job.id);
      if (job.abort.signal.aborted) return;
      const message = err instanceof Error ? err.message : String(err);
      log.warn('Media job failed', { job: job.id, error: message.slice(0, 300) });
      this.emit({
        projectId: job.projectId,
        assetId: job.assetId,
        kind: job.kind,
        status: 'error',
        error: message.slice(0, 300),
      });
    } finally {
      this.pump();
      // No analysis left to do: let the worker go after a while (the next
      // job respawns it — a couple of seconds on DirectML).
      if (isAnalysisKind(job.kind) && ![...this.jobs.values()].some((j) => isAnalysisKind(j.kind))) analysisEngine.scheduleRelease();
    }
  }

  private async produce(job: JobRecord): Promise<StudioMediaJobEvent> {
    const base = { projectId: job.projectId, assetId: job.assetId, kind: job.kind } as const;

    if (job.kind === 'transcript') {
      if (!job.sttModelId) throw new Error('Transcript job queued without a model');
      let lastPercent = -1;
      const { relPath, meta } = await transcribeAsset(
        job.projectId,
        job.assetId,
        job.sourcePath,
        job.sttModelId,
        job.abort.signal,
        (percent, message) => {
          // Throttle to whole-percent changes; renderers fold these into
          // transient UI state, not the document.
          const rounded = Math.round(percent);
          if (rounded === lastPercent || job.abort.signal.aborted) return;
          lastPercent = rounded;
          this.emit({ ...base, status: 'generating', percent: rounded, message });
        },
      );
      return { ...base, status: 'ready', relPath, transcript: meta };
    }

    if (isAnalysisKind(job.kind)) {
      if (!job.analysis) throw new Error('Analysis job queued without its spans');
      const { relPath, analysis } = await runAnalysisJob(
        { projectId: job.projectId, assetId: job.assetId, kind: job.kind, sourcePath: job.sourcePath, options: job.analysis },
        job.abort.signal,
        (percent, message) => this.emit({ ...base, status: 'generating', percent, ...(message ? { message } : {}) }),
      );
      return { ...base, status: 'ready', relPath, analysis };
    }

    if (job.kind === 'proxy') {
      // Same whole-percent throttle as transcripts; the renderer keeps these
      // ticks in transient UI state, never the document.
      let lastPercent = -1;
      const relPath = await generateProxy(
        job.projectId,
        job.assetId,
        job.sourcePath,
        job.abort.signal,
        (percent) => {
          const rounded = Math.round(percent);
          if (rounded === lastPercent || job.abort.signal.aborted) return;
          lastPercent = rounded;
          this.emit({ ...base, status: 'generating', percent: rounded });
        },
      );
      return { ...base, status: 'ready', relPath };
    }

    const relPath = await generateWaveform(job.projectId, job.assetId, job.sourcePath, job.abort.signal);
    return { ...base, status: 'ready', relPath };
  }
}

export const studioMediaJobs = new StudioMediaJobEngine();
