import { useCallback, useEffect, useState } from 'react';
import { ChevronLeft } from 'lucide-react';
import { useFlowGraph } from '../hooks/useFlowGraph';
import { RunStateProvider, useFlowRun, type RunState } from '../hooks/useFlowRun';
import { useFlowRuns } from '../hooks/useFlowRuns';
import type { GraphEdge, GraphJson, GraphNode } from '../types';
import type { NodeRunState } from '../services/run-flow';
import { FlowCanvas } from './FlowCanvas';
import { NodePalette } from './NodePalette';
import { NodeInspector } from './NodeInspector';
import { RunControls } from './RunControls';
import { RunHistoryDropdown } from './RunHistoryDropdown';

interface Props {
  flowId: string;
  onBack: () => void;
}

export function FlowEditor({ flowId, onBack }: Props) {
  const {
    status,
    project,
    error,
    nodes,
    edges,
    viewport,
    onNodesChange,
    onEdgesChange,
    onConnect,
    onViewportChange,
    addNode,
    updateNodeConfig,
    renameFlow,
  } = useFlowGraph(flowId);

  const [nameDraft, setNameDraft] = useState('');
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);

  // useFlowGraph holds reactflow-typed Node<NodeData>/Edge; the run-flow service uses the
  // structurally identical GraphJson shape. Cast through unknown is safe — no field rename.
  const graphForRun: GraphJson = {
    nodes: nodes as unknown as GraphNode[],
    edges: edges as unknown as GraphEdge[],
    viewport,
  };
  const { runs, refresh: refreshRuns, loadRun } = useFlowRuns(flowId);

  // Card thumbnails are now schematic SVGs regenerated by useFlowGraph on every
  // save, so we no longer need a post-run html2canvas capture here.
  const handleRunPersisted = useCallback(() => {
    void refreshRuns();
  }, [refreshRuns]);

  const { runState, run, cancel, hydrate } = useFlowRun({
    flowId,
    graph: graphForRun,
    flowName: project?.name ?? 'Untitled',
    flowFolderId: project?.galleryFolderId ?? null,
    onRunPersisted: handleRunPersisted,
  });

  const handleSelectRun = useCallback(
    async (runId: string) => {
      const record = await loadRun(runId);
      if (!record) return;
      let nodes: Record<string, NodeRunState> = {};
      try {
        const parsed = JSON.parse(record.nodeResults);
        if (parsed && typeof parsed === 'object') {
          nodes = parsed as Record<string, NodeRunState>;
        }
      } catch {
        // Treat unparseable results as no node previews — status badge still shows.
      }
      const hydrated: RunState = {
        runId: record.id,
        status: record.status,
        nodes,
        startedAt: record.startedAt,
        finishedAt: record.finishedAt,
        error: record.error,
      };
      hydrate(hydrated);
    },
    [loadRun, hydrate],
  );

  useEffect(() => {
    if (project) setNameDraft(project.name);
  }, [project]);

  // Clear selection if the selected node was deleted
  useEffect(() => {
    if (selectedNodeId && !nodes.some((n) => n.id === selectedNodeId)) {
      setSelectedNodeId(null);
    }
  }, [nodes, selectedNodeId]);

  const commitRename = () => {
    if (!project) return;
    const trimmed = nameDraft.trim();
    if (!trimmed || trimmed === project.name) {
      setNameDraft(project.name);
      return;
    }
    void renameFlow(trimmed);
  };

  const selectedNode = selectedNodeId ? nodes.find((n) => n.id === selectedNodeId) ?? null : null;

  return (
    <div className="flex flex-col h-full">
      <div
        className="flex items-center gap-2 h-[40px] px-3 bg-app-surface shrink-0"
        style={{ borderBottom: '0.5px solid var(--color-border)' }}
      >
        <button
          onClick={onBack}
          className="flex items-center gap-1 px-2 py-1 rounded text-text-muted hover:bg-app-hover hover:text-text-primary text-[12px]"
        >
          <ChevronLeft size={14} strokeWidth={1.5} />
          Flows
        </button>
        <span className="text-text-dim">/</span>
        {project ? (
          <input
            value={nameDraft}
            onChange={(e) => setNameDraft(e.target.value)}
            onBlur={commitRename}
            onKeyDown={(e) => {
              if (e.key === 'Enter') (e.target as HTMLInputElement).blur();
              if (e.key === 'Escape') {
                setNameDraft(project.name);
                (e.target as HTMLInputElement).blur();
              }
            }}
            className="bg-transparent text-[13px] font-medium text-text-secondary outline-none focus:bg-app-hover px-1.5 py-0.5 rounded"
          />
        ) : (
          <span className="text-[13px] text-text-muted">Loading…</span>
        )}
        <div className="flex-1" />
        {error && <span className="text-[11px] text-accent-red mr-3">{error}</span>}
        {status === 'ready' && (
          <>
            <RunHistoryDropdown
              runs={runs}
              activeRunId={runState.runId}
              onSelect={(id) => void handleSelectRun(id)}
              disabled={runState.status === 'running'}
            />
            <RunControls runState={runState} onRun={run} onCancel={cancel} />
          </>
        )}
      </div>

      <RunStateProvider value={runState}>
        <div className="flex-1 flex min-h-0">
          {status === 'ready' && (
            <aside
              className="w-[200px] shrink-0 bg-app-surface"
              style={{ borderRight: '0.5px solid var(--color-border)' }}
            >
              <NodePalette />
            </aside>
          )}

          <div className="flex-1 min-w-0 bg-app-deep">
            {status === 'ready' ? (
              <FlowCanvas
                nodes={nodes}
                edges={edges}
                viewport={viewport}
                onNodesChange={onNodesChange}
                onEdgesChange={onEdgesChange}
                onConnect={onConnect}
                onViewportChange={onViewportChange}
                onSelectionChange={setSelectedNodeId}
                onDropNode={addNode}
              />
            ) : status === 'error' ? (
              <div className="flex items-center justify-center h-full text-accent-red text-sm">
                {error ?? 'Failed to load flow'}
              </div>
            ) : (
              <div className="flex items-center justify-center h-full text-text-muted text-sm">
                Loading…
              </div>
            )}
          </div>

          {status === 'ready' && selectedNode && (
            <aside
              className="w-[300px] shrink-0 bg-app-surface"
              style={{ borderLeft: '0.5px solid var(--color-border)' }}
            >
              <NodeInspector
                typeId={selectedNode.data.typeId}
                config={selectedNode.data.config}
                onPatchConfig={(patch) => updateNodeConfig(selectedNode.id, patch)}
              />
            </aside>
          )}
        </div>
      </RunStateProvider>
    </div>
  );
}
