import { registerModuleHandlers } from './module-handlers';
import { registerAppShellIpc } from './registrations/app-shell';
import { registerFileIpc } from './registrations/file';
import { registerBundleIpc } from './registrations/bundle';
import { registerRenderIpc } from './registrations/render';
import { registerSettingsIpc } from './registrations/settings';
import { registerWhisperIpc } from './registrations/whisper';
import { registerLlmIpc } from './registrations/llm';
import { registerFlowsIpc } from './registrations/flows';
import { registerImageStudioIpc } from './registrations/image-studio';
import { registerThumbnailIpc } from './registrations/thumbnail';
import { registerLogIpc } from './registrations/log';
import { registerFrameExtractorIpc } from './registrations/frame-extractor';
import { registerAudioIpc } from './registrations/audio';
import { registerAudioGenerationIpc } from './registrations/audio-generation';
import { registerEmbeddingIpc } from './registrations/embedding';
import { registerSdImageIpc } from './registrations/sd-image';
import { registerSdVideoIpc } from './registrations/sd-video';
import { registerTsxJobsIpc } from './registrations/tsx-jobs';
import { registerTemplatesIpc } from './registrations/templates';
import { registerModelLibraryIpc } from './registrations/model-library';
import { registerLocalLlmIpc } from './registrations/local-llm';
import { registerSystemIpc } from './registrations/system';
import { registerDownloadIpc } from './registrations/download';
import { registerAiRuntimeIpc } from './registrations/ai-runtime';
import { registerPythonModelsIpc } from './registrations/python-models';
import { registerRembgIpc } from './registrations/rembg';
import { registerSd3dIpc } from './registrations/sd3d';
import { registerThreedStudioIpc } from './registrations/threed-studio';
import { registerModerationIpc } from './registrations/moderation';
import { registerContentSafetyIpc } from './registrations/content-safety';
import { registerAiUsageIpc } from './registrations/ai-usage';
import { registerProviderKeysIpc } from './registrations/provider-keys';
import { registerProviderModelsIpc } from './registrations/provider-models';
import { registerImageModelParamsIpc } from './registrations/image-model-params';
import { registerVideoIpc } from './registrations/video';
import { registerSttIpc } from './registrations/stt';
import { registerVideoStudioIpc } from './registrations/video-studio';
import { registerStudioIpc } from './registrations/studio';
import { registerMemoryIpc } from './registrations/memory';
import { registerNewsIpc } from './registrations/news';
import { registerUpdaterIpc } from './registrations/updater';
import { registerLibraryIpc } from './registrations/library';
import { registerAgentsIpc } from './registrations/agents';
import { registerHomeIpc } from './registrations/home';
import { logEngine } from '../../logging/log-engine';

export function registerAllIPC(): void {
  // Module operations (native player) — registers its own handlers.
  registerModuleHandlers();

  // Per-feature handler registration.
  registerAppShellIpc();
  registerFileIpc();
  registerBundleIpc();
  registerRenderIpc();
  registerSettingsIpc();
  registerWhisperIpc();
  registerLlmIpc();
  registerFlowsIpc();
  registerImageStudioIpc();
  registerThumbnailIpc();
  registerLogIpc();
  registerFrameExtractorIpc();
  registerAudioIpc();
  registerAudioGenerationIpc();
  registerEmbeddingIpc();
  registerSdImageIpc();
  registerSdVideoIpc();
  registerTsxJobsIpc();
  registerTemplatesIpc();
  registerModelLibraryIpc();
  registerLocalLlmIpc();
  registerSystemIpc();
  registerDownloadIpc();
  registerAiRuntimeIpc();
  registerPythonModelsIpc();
  registerRembgIpc();
  registerSd3dIpc();
  registerThreedStudioIpc();
  registerModerationIpc();
  registerContentSafetyIpc();
  registerAiUsageIpc();
  registerProviderKeysIpc();
  registerProviderModelsIpc();
  registerImageModelParamsIpc();
  registerVideoIpc();
  registerSttIpc();
  registerVideoStudioIpc();
  registerStudioIpc();
  registerMemoryIpc();
  registerNewsIpc();
  registerUpdaterIpc();
  registerLibraryIpc();
  registerAgentsIpc();
  registerHomeIpc();

  logEngine.info('IPC', 'IPC handlers registered');
}
